//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package presentation ;import (_gg "archive/zip";_dcf "bytes";_ffe "encoding/xml";_ab "errors";_dc "fmt";_ge "github.com/unidoc/unioffice/v2";_adc "github.com/unidoc/unioffice/v2/common";_dd "github.com/unidoc/unioffice/v2/common/logger";_ad "github.com/unidoc/unioffice/v2/common/tempstorage";
_be "github.com/unidoc/unioffice/v2/drawing";_ff "github.com/unidoc/unioffice/v2/internal/formatutils";_ef "github.com/unidoc/unioffice/v2/internal/license";_ea "github.com/unidoc/unioffice/v2/measurement";_ag "github.com/unidoc/unioffice/v2/schema/soo/dml";
_g "github.com/unidoc/unioffice/v2/schema/soo/dml/chart";_d "github.com/unidoc/unioffice/v2/schema/soo/ofc/sharedTypes";_aa "github.com/unidoc/unioffice/v2/schema/soo/pkg/relationships";_db "github.com/unidoc/unioffice/v2/schema/soo/pml";_a "github.com/unidoc/unioffice/v2/zippkg";
_ee "image";_efd "image/jpeg";_fd "io";_gb "math";_eg "os";_af "path";_ac "sort";_e "strconv";_b "strings";);

// Properties returns the properties of the TextBox.
func (_eab Image )Properties ()_be .ShapeProperties {if _eab ._ffc .SpPr ==nil {_eab ._ffc .SpPr =_ag .NewCT_ShapeProperties ();};return _be .MakeShapeProperties (_eab ._ffc .SpPr );};

// X returns the inner wrapped XML type.
func (_gede SlideLayout )X ()*_db .SldLayout {return _gede ._fcea };

// LastViewAttr returns the LastViewAttr property.
func (_dfac ViewProperties )LastViewAttr ()_db .ST_ViewType {return _dfac ._dgeb .LastViewAttr };

// X returns the inner wrapped XML type.
func (_bdg PlaceHolder )X ()*_db .CT_Shape {return _bdg ._abfg };

// Less is for implementing sorting of two locations. Symbols share the same location if they are in the same paragraph or table. One location is 'less' than another first by y coordinate, if y coordinates are equal or differ by less than yEpsilon, then x coordinates are compared, then if they are also equal, indexes of locations in the table are compared, then positions of locations in a paragraph.
func (_gd sort2d )Less (i ,j int )bool {_dcfg ,_fdc :=_gd [i ],_gd [j ];_efg ,_faa :=_dcfg ._bc ,_fdc ._bc ;_cf ,_cbe :=len (_efg )-1,len (_faa )-1;_gee ,_dfd :=0,0;for {_cde ,_dbf ,_ega ,_geb ,_edf ,_aed ,_ddf ,_faag :=_efg [_gee ]._cc ,_faa [_dfd ]._cc ,_efg [_gee ]._cca ,_faa [_dfd ]._cca ,_efg [_gee ]._c ,_faa [_dfd ]._c ,_efg [_gee ]._efbf ,_faa [_dfd ]._efbf ;
if _cde ==_dbf ||((_gb .Abs (float64 (_cde )-float64 (_dbf ))< _add )&&((_cde >=_dbf &&_cde <=_geb )||(_dbf >=_cde &&_dbf <=_ega ))&&(_ddf < _aed ||_edf > _faag )){if _edf ==_aed {if _gee < _cf &&_dfd < _cbe {_gee ++;_dfd ++;continue ;};if _gee >=_cf &&_dfd >=_cbe {break ;
};return _gee >=_cf ;}else {return _edf < _aed ;};}else {return _cde < _dbf ;};};_cee ,_gcc ,_cgd ,_eca :=_dcfg ._fg ,_fdc ._fg ,_dcfg ._afa ,_fdc ._afa ;if _cee ==_gcc {return _cgd <=_eca ;};return _cee < _gcc ;};func (_bbbf *Slide )getSlideRels ()_adc .Relationships {_fbg :=_bbbf ._agab ;
for _dbff ,_aedf :=range _fbg .Slides (){if *_bbbf ._fea ==*_aedf ._fea {return _fbg ._bcd [_dbff ];};};return _adc .Relationships {};};

// NewSlideScreenSize returns slide screen size with default MS PowerPoint slide screen size 16x9.
func NewSlideScreenSize ()SlideScreenSize {return NewSlideScreenSizeWithValue (SlideScreenSize16x9 [0],SlideScreenSize16x9 [1]);};var _gcf =true ;

// AddTable adds a new table to a placeholder.
func (_cda PlaceHolder )AddTable ()*_adc .Table {_cda .Clear ();_aga :=_db .NewCT_GroupShapeChoice ();_cda ._gdb .CSld .SpTree .GroupShapeChoice =append (_cda ._gdb .CSld .SpTree .GroupShapeChoice ,_aga );_facf :=_db .NewCT_GraphicalObjectFrame ();_aga .GraphicFrame =_facf ;
_facf .Xfrm .Off =_ag .NewCT_Point2D ();_ead :=int64 (1);_facf .Xfrm .Off .XAttr =_ag .ST_Coordinate {ST_CoordinateUnqualified :&_ead };_facf .Xfrm .Off .YAttr =_ag .ST_Coordinate {ST_CoordinateUnqualified :&_ead };_agae :=_facf .Graphic .CT_GraphicalObject .GraphicData ;
_agae .UriAttr ="\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002eo\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073.\u006f\u0072\u0067\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u006dl/\u0032\u0030\u0030\u0036\u002f\u0074\u0061\u0062\u006c\u0065";
_eed :=_adc .NewTableWithXfrm (_facf .Xfrm );_agae .Any =append (_agae .Any ,_eed .X ());return _eed ;};

// Text returns text from a slide as one string separated with line breaks.
func (_gbb *SlideText )Text ()string {_fad :=_dcf .NewBuffer ([]byte {});for _ ,_bca :=range _gbb .Items {if _bca .Text !=""{_fad .WriteString (_bca .Text );_fad .WriteString ("\u000a");};};return _fad .String ();};type sort2d []*TextItem ;

// PresentationProperties contains document specific properties.
type PresentationProperties struct{_gbdc *_db .PresentationPr };

// Type returns the type of the slide layout.
func (_geed SlideLayout )Type ()_db .ST_SlideLayoutType {return _geed ._fcea .TypeAttr };

// SetOffsetY sets vertical offset of text box in distance units (see measurement package).
func (_deec TextBox )SetOffsetY (offY float64 ){_aeb :=_deec .getOff ();_fabc :=_ea .ToEMU (offY );_aeb .YAttr =_ag .ST_Coordinate {ST_CoordinateUnqualified :&_fabc };};type rectangle struct{_c int64 ;_cc int64 ;_efbf int64 ;_cca int64 ;};

// SlideLayouts returns the slide layouts defined in the presentation.
func (_agd *Presentation )SlideLayouts ()[]SlideLayout {_dfa :=[]SlideLayout {};for _ ,_eccg :=range _agd ._cge {if _eccg ==nil {continue ;};if _eccg .CSld .NameAttr ==nil {continue ;};_dfa =append (_dfa ,SlideLayout {_eccg });};return _dfa ;};

// HtmlPubPr returns the HtmlPubPr property.
func (_gbfb PresentationProperties )HtmlPubPr ()*_db .CT_HtmlPublishProperties {return _gbfb ._gbdc .HtmlPubPr ;};

// X returns the inner wrapped XML type.
func (_fgcf *Presentation )X ()*_db .Presentation {return _fgcf ._agc };

// SlideViewPr returns the SlideViewPr property.
func (_fbe ViewProperties )SlideViewPr ()*_db .CT_SlideViewProperties {return _fbe ._dgeb .SlideViewPr };

// SetText sets the text of a placeholder for the initial paragraph. This is a
// shortcut method that is useful for things like titles which only contain a
// single paragraph.
func (_fgcc PlaceHolder )SetText (text string ){_fgcc .Clear ();_gae :=_ag .NewEG_TextRun ();_gae .TextRunChoice .R =_ag .NewCT_RegularTextRun ();_gae .TextRunChoice .R .T =text ;if len (_fgcc ._abfg .TxBody .P )==0{_fgcc ._abfg .TxBody .P =append (_fgcc ._abfg .TxBody .P ,_ag .NewCT_TextParagraph ());
};_fgcc ._abfg .TxBody .P [0].EG_TextRun =nil ;_fgcc ._abfg .TxBody .P [0].EG_TextRun =append (_fgcc ._abfg .TxBody .P [0].EG_TextRun ,_gae );};

// MoveSlide moves a slide with given number to position targetPos within a presentation.
func (_dda *Presentation )MoveSlide (slideNumber ,targetPos int )error {if slideNumber < 0||slideNumber >=len (_dda ._ggcc ){return _ab .New ("\u0073\u006c\u0069\u0064eN\u0075\u006d\u0062\u0065\u0072\u0020\u0069\u0073\u0020\u0069\u006e\u0076\u0061\u006ci\u0064");
};if targetPos < 0||targetPos >=len (_dda ._ggcc ){return _ab .New ("t\u0061r\u0067\u0065\u0074\u0050\u006f\u0073\u0020\u0069s\u0020\u0069\u006e\u0076al\u0069\u0064");};if slideNumber ==targetPos {return nil ;};_bgf :=_dda ._ggcc [slideNumber ];_bdc :=_dda ._bcd [slideNumber ];
if slideNumber < targetPos {copy (_dda ._ggcc [slideNumber :targetPos ],_dda ._ggcc [slideNumber +1:targetPos +1]);copy (_dda ._bcd [slideNumber :targetPos ],_dda ._bcd [slideNumber +1:targetPos +1]);}else {copy (_dda ._ggcc [targetPos +1:slideNumber +1],_dda ._ggcc [targetPos :slideNumber ]);
copy (_dda ._bcd [targetPos +1:slideNumber +1],_dda ._bcd [targetPos :slideNumber ]);};_dda ._ggcc [targetPos ]=_bgf ;_dda ._bcd [targetPos ]=_bdc ;return nil ;};

// New initializes and returns a new presentation
func New ()*Presentation {_dcg :=_dg ();_dcg .ContentTypes .AddOverride ("/\u0070\u0070\u0074\u002fpr\u0065s\u0065\u006e\u0074\u0061\u0074i\u006f\u006e\u002e\u0078\u006d\u006c","\u0061\u0070\u0070\u006c\u0069\u0063\u0061t\u0069\u006f\u006e\u002f\u0076\u006e\u0064\u002e\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072m\u0061\u0074\u0073\u002d\u006ff\u0066\u0069\u0063\u0065\u0064\u006f\u0063\u0075\u006de\u006e\u0074\u002e\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061\u0074\u0069\u006f\u006e\u006d\u006c\u002e\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061\u0074\u0069\u006f\u006e\u002e\u006d\u0061\u0069\u006e\u002b\u0078\u006d\u006c");
_dcg .ContentTypes .AddOverride ("\u0070\u0070\u0074\u002f\u0070\u0072\u0065\u0073\u0050\u0072\u006f\u0070s\u002e\u0078\u006d\u006c","\u0061\u0070\u0070\u006c\u0069c\u0061\u0074\u0069\u006f\u006e\u002fv\u006e\u0064\u002e\u006f\u0070\u0065\u006ex\u006d\u006c\u0066o\u0072\u006d\u0061\u0074s\u002d\u006f\u0066\u0066\u0069\u0063e\u0064\u006f\u0063\u0075\u006d\u0065\u006e\u0074\u002e\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061t\u0069\u006f\u006e\u006d\u006c\u002e\u0070\u0072\u0065\u0073\u0050\u0072\u006f\u0070\u0073\u002b\u0078\u006d\u006c");
_dcg .ContentTypes .AddOverride ("\u0070\u0070\u0074\u002f\u0076\u0069\u0065\u0077\u0050\u0072\u006f\u0070s\u002e\u0078\u006d\u006c","\u0061\u0070\u0070\u006c\u0069c\u0061\u0074\u0069\u006f\u006e\u002fv\u006e\u0064\u002e\u006f\u0070\u0065\u006ex\u006d\u006c\u0066o\u0072\u006d\u0061\u0074s\u002d\u006f\u0066\u0066\u0069\u0063e\u0064\u006f\u0063\u0075\u006d\u0065\u006e\u0074\u002e\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061t\u0069\u006f\u006e\u006d\u006c\u002e\u0076\u0069\u0065\u0077\u0050\u0072\u006f\u0070\u0073\u002b\u0078\u006d\u006c");
_dcg .ContentTypes .AddOverride ("\u0070\u0070\u0074\u002fta\u0062\u006c\u0065\u0053\u0074\u0079\u006c\u0065\u0073\u002e\u0078\u006d\u006c","\u0061\u0070\u0070\u006c\u0069c\u0061\u0074\u0069\u006f\u006e\u002f\u0076n\u0064\u002e\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073\u002d\u006f\u0066\u0066\u0069\u0063\u0065\u0064\u006f\u0063\u0075\u006d\u0065\u006e\u0074\u002e\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061t\u0069\u006f\u006e\u006d\u006c\u002e\u0074\u0061\u0062\u006c\u0065\u0053t\u0079\u006c\u0065\u0073\u002b\u0078m\u006c");
_dcg .Rels .AddRelationship ("\u0064\u006f\u0063\u0050\u0072\u006f\u0070\u0073\u002f\u0063\u006f\u0072e\u002e\u0078\u006d\u006c","\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061s\u002e\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066o\u0072\u006d\u0061\u0074\u0073\u002e\u006f\u0072\u0067\u002f\u0070\u0061\u0063\u006ba\u0067\u0065\u002f\u0032\u0030\u0030\u0036\u002f\u0072\u0065\u006c\u0061\u0074\u0069\u006f\u006e\u0073\u0068\u0069\u0070\u0073\u002f\u006d\u0065\u0074\u0061\u0064\u0061\u0074\u0061/\u0063\u006f\u0072\u0065\u002d\u0070\u0072\u006f\u0070e\u0072\u0074i\u0065\u0073");
_dcg .Rels .AddRelationship ("\u0064\u006fc\u0050\u0072\u006fp\u0073\u002f\u0061\u0070\u0070\u002e\u0078\u006d\u006c","\u0068t\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002eo\u0070\u0065\u006ex\u006d\u006c\u0066\u006f\u0072\u006da\u0074\u0073.\u006f\u0072\u0067\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u0044\u006f\u0063\u0075\u006d\u0065\u006e\u0074\u002f\u0032\u0030\u0030\u0036\u002f\u0072\u0065\u006c\u0061\u0074i\u006f\u006e\u0073\u0068\u0069p\u0073\u002f\u0065x\u0074\u0065\u006e\u0064\u0065d\u002d\u0070\u0072\u006f\u0070\u0065\u0072\u0074\u0069\u0065\u0073");
_dcg .Rels .AddRelationship ("p\u0070t\u002f\u0070\u0072\u0065\u0073\u0065\u006e\u0074a\u0074\u0069\u006f\u006e.x\u006d\u006c","\u0068\u0074\u0074\u0070\u003a\u002f\u002fs\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006da\u0074\u0073\u002e\u006f\u0072g\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u0044\u006fc\u0075\u006d\u0065\u006e\u0074\u002f\u0032\u0030\u0030\u0036\u002f\u0072\u0065\u006c\u0061\u0074\u0069\u006f\u006e\u0073\u0068\u0069\u0070\u0073\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u0044\u006f\u0063\u0075\u006d\u0065\u006e\u0074");
_dcg ._agc .SldMasterIdLst =_db .NewCT_SlideMasterIdList ();_fga :=_db .NewSldMaster ();_fga .ClrMap .Bg1Attr =_ag .ST_ColorSchemeIndexLt1 ;_fga .ClrMap .Bg2Attr =_ag .ST_ColorSchemeIndexLt2 ;_fga .ClrMap .Tx1Attr =_ag .ST_ColorSchemeIndexDk1 ;_fga .ClrMap .Tx2Attr =_ag .ST_ColorSchemeIndexDk2 ;
_fga .ClrMap .Accent1Attr =_ag .ST_ColorSchemeIndexAccent1 ;_fga .ClrMap .Accent2Attr =_ag .ST_ColorSchemeIndexAccent2 ;_fga .ClrMap .Accent3Attr =_ag .ST_ColorSchemeIndexAccent3 ;_fga .ClrMap .Accent4Attr =_ag .ST_ColorSchemeIndexAccent4 ;_fga .ClrMap .Accent5Attr =_ag .ST_ColorSchemeIndexAccent5 ;
_fga .ClrMap .Accent6Attr =_ag .ST_ColorSchemeIndexAccent6 ;_fga .ClrMap .HlinkAttr =_ag .ST_ColorSchemeIndexHlink ;_fga .ClrMap .FolHlinkAttr =_ag .ST_ColorSchemeIndexFolHlink ;_dcg ._dfdb =append (_dcg ._dfdb ,_fga );_dcg ._dbb =append (_dcg ._dbb ,len (_dcg ._dfdb ));
_ggcb :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .SlideMasterType ,1);_dcg .ContentTypes .AddOverride (_ggcb ,_ge .SlideMasterContentType );_caa :=_dcg ._ddcf .AddAutoRelationship (_ge .DocTypePresentation ,_ge .OfficeDocumentType ,1,_ge .SlideMasterType );
_dbca :=_db .NewCT_SlideMasterIdListEntry ();_dbca .IdAttr =_ge .Uint32 (2147483648);_dbca .RIdAttr =_caa .ID ();_dcg ._agc .SldMasterIdLst .SldMasterId =append (_dcg ._agc .SldMasterIdLst .SldMasterId ,_dbca );_bce :=_adc .NewRelationships ();_dcg ._bcg =append (_dcg ._bcg ,_bce );
_cgdd :=_db .NewSldLayout ();_bdf :=_bce .AddAutoRelationship (_ge .DocTypePresentation ,_ge .SlideMasterType ,1,_ge .SlideLayoutType );_geea :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .SlideLayoutType ,1);_dcg .ContentTypes .AddOverride (_geea ,_ge .SlideLayoutContentType );
_bce .AddAutoRelationship (_ge .DocTypePresentation ,_ge .SlideMasterType ,1,_ge .ThemeType );_dcg ._cge =append (_dcg ._cge ,_cgdd );_fga .SldLayoutIdLst =_db .NewCT_SlideLayoutIdList ();_dfc :=_db .NewCT_SlideLayoutIdListEntry ();_dfc .IdAttr =_ge .Uint32 (2147483649);
_dfc .RIdAttr =_bdf .ID ();_fga .SldLayoutIdLst .SldLayoutId =append (_fga .SldLayoutIdLst .SldLayoutId ,_dfc );_egeb :=_adc .NewRelationships ();_dcg ._bdb =append (_dcg ._bdb ,_egeb );_egeb .AddAutoRelationship (_ge .DocTypePresentation ,_ge .SlideType ,1,_ge .SlideMasterType );
_dcg ._agc .NotesSz .CxAttr =6858000;_dcg ._agc .NotesSz .CyAttr =9144000;_gfe :=_ag .NewTheme ();_gfe .NameAttr =_ge .String ("\u0075n\u0069o\u0066\u0066\u0069\u0063\u0065\u0020\u0054\u0068\u0065\u006d\u0065");_gfe .ThemeElements .ClrScheme .NameAttr ="\u004f\u0066\u0066\u0069\u0063\u0065";
_gfe .ThemeElements .ClrScheme .Dk1 .SysClr =_ag .NewCT_SystemColor ();_gfe .ThemeElements .ClrScheme .Dk1 .SysClr .LastClrAttr =_ge .String ("\u0030\u0030\u0030\u0030\u0030\u0030");_gfe .ThemeElements .ClrScheme .Dk1 .SysClr .ValAttr =_ag .ST_SystemColorValWindowText ;
_gfe .ThemeElements .ClrScheme .Lt1 .SysClr =_ag .NewCT_SystemColor ();_gfe .ThemeElements .ClrScheme .Lt1 .SysClr .LastClrAttr =_ge .String ("\u0066\u0066\u0066\u0066\u0066\u0066");_gfe .ThemeElements .ClrScheme .Lt1 .SysClr .ValAttr =_ag .ST_SystemColorValWindow ;
_gfe .ThemeElements .ClrScheme .Dk2 .SrgbClr =_ag .NewCT_SRgbColor ();_gfe .ThemeElements .ClrScheme .Dk2 .SrgbClr .ValAttr ="\u0034\u0034\u0035\u0034\u0036\u0061";_gfe .ThemeElements .ClrScheme .Lt2 .SrgbClr =_ag .NewCT_SRgbColor ();_gfe .ThemeElements .ClrScheme .Lt2 .SrgbClr .ValAttr ="\u0065\u0037\u0065\u0037\u0065\u0036";
_gfe .ThemeElements .ClrScheme .Accent1 .SrgbClr =_ag .NewCT_SRgbColor ();_gfe .ThemeElements .ClrScheme .Accent1 .SrgbClr .ValAttr ="\u0034\u0034\u0037\u0032\u0063\u0034";_gfe .ThemeElements .ClrScheme .Accent2 .SrgbClr =_ag .NewCT_SRgbColor ();_gfe .ThemeElements .ClrScheme .Accent2 .SrgbClr .ValAttr ="\u0065\u0064\u0037\u0064\u0033\u0031";
_gfe .ThemeElements .ClrScheme .Accent3 .SrgbClr =_ag .NewCT_SRgbColor ();_gfe .ThemeElements .ClrScheme .Accent3 .SrgbClr .ValAttr ="\u0061\u0035\u0061\u0035\u0061\u0035";_gfe .ThemeElements .ClrScheme .Accent4 .SrgbClr =_ag .NewCT_SRgbColor ();_gfe .ThemeElements .ClrScheme .Accent4 .SrgbClr .ValAttr ="\u0066\u0066\u0063\u0030\u0030\u0030";
_gfe .ThemeElements .ClrScheme .Accent5 .SrgbClr =_ag .NewCT_SRgbColor ();_gfe .ThemeElements .ClrScheme .Accent5 .SrgbClr .ValAttr ="\u0035\u0062\u0039\u0062\u0064\u0035";_gfe .ThemeElements .ClrScheme .Accent6 .SrgbClr =_ag .NewCT_SRgbColor ();_gfe .ThemeElements .ClrScheme .Accent6 .SrgbClr .ValAttr ="\u0037\u0030\u0061\u0064\u0034\u0037";
_gfe .ThemeElements .ClrScheme .Hlink .SrgbClr =_ag .NewCT_SRgbColor ();_gfe .ThemeElements .ClrScheme .Hlink .SrgbClr .ValAttr ="\u0030\u0035\u0036\u0033\u0063\u0031";_gfe .ThemeElements .ClrScheme .FolHlink .SrgbClr =_ag .NewCT_SRgbColor ();_gfe .ThemeElements .ClrScheme .FolHlink .SrgbClr .ValAttr ="\u0039\u0035\u0034\u0066\u0037\u0032";
_gfe .ThemeElements .FontScheme .NameAttr ="\u004f\u0066\u0066\u0069\u0063\u0065";_gfe .ThemeElements .FontScheme .MajorFont .Latin .TypefaceAttr ="\u0043\u0061\u006c\u0069\u0062\u0072\u0069\u0020\u004c\u0069\u0067\u0068\u0074";_gfe .ThemeElements .FontScheme .MinorFont .Latin .TypefaceAttr ="\u0043a\u006c\u0069\u0062\u0072\u0069";
_gfe .ThemeElements .FmtScheme .NameAttr =_ge .String ("\u004f\u0066\u0066\u0069\u0063\u0065");_cbgg :=_ag .NewEG_FillProperties ();_gfe .ThemeElements .FmtScheme .FillStyleLst .EG_FillProperties =append (_gfe .ThemeElements .FmtScheme .FillStyleLst .EG_FillProperties ,_cbgg );
_cbgg .FillPropertiesChoice .SolidFill =&_ag .CT_SolidColorFillProperties {SchemeClr :&_ag .CT_SchemeColor {ValAttr :_ag .ST_SchemeColorValPhClr }};_cbgg =_ag .NewEG_FillProperties ();_gfe .ThemeElements .FmtScheme .FillStyleLst .EG_FillProperties =append (_gfe .ThemeElements .FmtScheme .FillStyleLst .EG_FillProperties ,_cbgg );
_gfe .ThemeElements .FmtScheme .FillStyleLst .EG_FillProperties =append (_gfe .ThemeElements .FmtScheme .FillStyleLst .EG_FillProperties ,_cbgg );_cbgg .FillPropertiesChoice .GradFill =&_ag .CT_GradientFillProperties {RotWithShapeAttr :_ge .Bool (true ),GsLst :&_ag .CT_GradientStopList {},ShadePropertiesChoice :&_ag .EG_ShadePropertiesChoice {Lin :&_ag .CT_LinearShadeProperties {}}};
_cbgg .FillPropertiesChoice .GradFill .ShadePropertiesChoice .Lin .AngAttr =_ge .Int32 (5400000);_cbgg .FillPropertiesChoice .GradFill .ShadePropertiesChoice .Lin .ScaledAttr =_ge .Bool (false );_bed :=_ag .NewCT_GradientStop ();_bed .PosAttr .ST_PositiveFixedPercentageDecimal =_ge .Int32 (0);
_bed .SchemeClr =&_ag .CT_SchemeColor {ValAttr :_ag .ST_SchemeColorValPhClr };_cbgg .FillPropertiesChoice .GradFill .GsLst .Gs =append (_cbgg .FillPropertiesChoice .GradFill .GsLst .Gs ,_bed );_bed =_ag .NewCT_GradientStop ();_bed .PosAttr .ST_PositiveFixedPercentageDecimal =_ge .Int32 (50000);
_bed .SchemeClr =&_ag .CT_SchemeColor {ValAttr :_ag .ST_SchemeColorValPhClr };_cbgg .FillPropertiesChoice .GradFill .GsLst .Gs =append (_cbgg .FillPropertiesChoice .GradFill .GsLst .Gs ,_bed );_gfe .ThemeElements .FmtScheme .LnStyleLst =_ag .NewCT_LineStyleList ();
for _afe :=0;_afe < 3;_afe ++{_dgb :=_ag .NewCT_LineProperties ();_dgb .WAttr =_ge .Int32 (int32 (6350*(_afe +1)));_dgb .CapAttr =_ag .ST_LineCapFlat ;_dgb .CmpdAttr =_ag .ST_CompoundLineSng ;_dgb .AlgnAttr =_ag .ST_PenAlignmentCtr ;_gfe .ThemeElements .FmtScheme .LnStyleLst .Ln =append (_gfe .ThemeElements .FmtScheme .LnStyleLst .Ln ,_dgb );
};_gfe .ThemeElements .FmtScheme .EffectStyleLst =_ag .NewCT_EffectStyleList ();for _aabb :=0;_aabb < 3;_aabb ++{_fdfa :=_ag .NewCT_EffectStyleItem ();_fdfa .EffectPropertiesChoice .EffectLst =_ag .NewCT_EffectList ();_gfe .ThemeElements .FmtScheme .EffectStyleLst .EffectStyle =append (_gfe .ThemeElements .FmtScheme .EffectStyleLst .EffectStyle ,_fdfa );
};_cgc :=_ag .NewEG_FillProperties ();_cgc .FillPropertiesChoice .SolidFill =&_ag .CT_SolidColorFillProperties {SchemeClr :&_ag .CT_SchemeColor {ValAttr :_ag .ST_SchemeColorValPhClr }};_gfe .ThemeElements .FmtScheme .BgFillStyleLst .EG_FillProperties =append (_gfe .ThemeElements .FmtScheme .BgFillStyleLst .EG_FillProperties ,_cgc );
_gfe .ThemeElements .FmtScheme .BgFillStyleLst .EG_FillProperties =append (_gfe .ThemeElements .FmtScheme .BgFillStyleLst .EG_FillProperties ,_cgc );_gfe .ThemeElements .FmtScheme .BgFillStyleLst .EG_FillProperties =append (_gfe .ThemeElements .FmtScheme .BgFillStyleLst .EG_FillProperties ,_cbgg );
_dcg ._gfd =append (_dcg ._gfd ,_gfe );_efc :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .ThemeType ,1);_dcg .ContentTypes .AddOverride (_efc ,_ge .ThemeContentType );_dcg ._ddcf .AddAutoRelationship (_ge .DocTypePresentation ,_ge .OfficeDocumentType ,1,_ge .ThemeType );
_afd :=_adc .NewRelationships ();_dcg ._gbfbc =append (_dcg ._gbfbc ,_afd );_dcg ._fbc =append (_dcg ._fbc ,len (_dcg ._gfd ));return _dcg ;};

// Slide represents a slide of a presentation.
type Slide struct{_cddgg *_db .CT_SlideIdListEntry ;_fea *_db .Sld ;_agab *Presentation ;_dgg *_ag .CT_ColorMapping ;};

// X returns the inner wrapped XML type.
func (_fgdc ViewProperties )X ()*_db .ViewPr {return _fgdc ._dgeb };

// GetLayoutByName retrieves a slide layout given a layout name.
func (_edee *Presentation )GetLayoutByName (name string )(SlideLayout ,error ){for _ ,_cgbe :=range _edee ._cge {if _cgbe .CSld .NameAttr !=nil &&name ==*_cgbe .CSld .NameAttr {return SlideLayout {_cgbe },nil ;};};return SlideLayout {},_ab .New ("\u0075\u006eab\u006c\u0065\u0020t\u006f\u0020\u0066\u0069nd \u006cay\u006f\u0075\u0074\u0020\u0077\u0069\u0074h \u0074\u0068\u0061\u0074\u0020\u006e\u0061m\u0065");
};

// PlaceHolder is a place holder from a slide.
type PlaceHolder struct{_abfg *_db .CT_Shape ;_gdb *_db .Sld ;};

// ExtLst returns the ExtLst property.
func (_bdgd ViewProperties )ExtLst ()*_db .CT_ExtensionList {return _bdgd ._dgeb .ExtLst };

// TableInfo is used for keep information about a table, a row and a cell where the text is located.
type TableInfo struct{Table *_ag .CT_Table ;Row *_ag .CT_TableRow ;Cell *_ag .CT_TableCell ;RowIndex int ;ColIndex int ;};

// ViewProperties contains presentation specific properties.
type ViewProperties struct{_dgeb *_db .ViewPr };

// Open opens and reads a document from a file (.pptx).
func Open (filename string )(*Presentation ,error ){_dbfb ,_bg :=_eg .Open (filename );if _bg !=nil {return nil ,_dc .Errorf ("e\u0072r\u006f\u0072\u0020\u006f\u0070\u0065\u006e\u0069n\u0067\u0020\u0025\u0073: \u0025\u0073",filename ,_bg );};defer _dbfb .Close ();
_eeb ,_bg :=_eg .Stat (filename );if _bg !=nil {return nil ,_dc .Errorf ("e\u0072r\u006f\u0072\u0020\u006f\u0070\u0065\u006e\u0069n\u0067\u0020\u0025\u0073: \u0025\u0073",filename ,_bg );};_ =_eeb ;return Read (_dbfb ,_eeb .Size ());};

// CopySlide copies existing slide from another presentation and inserts it as a last one.
func (_aedg *Presentation )CopySlide (s Slide )(Slide ,error ){_cfa :=_db .NewCT_SlideIdListEntry ();_cfa .IdAttr =_aedg .nextSlideID ();_aedg ._agc .SldIdLst .SldId =append (_aedg ._agc .SldIdLst .SldId ,_cfa );_gag :=s .GetSlideLayout ();_daf :=true ;
for _ ,_afda :=range _aedg ._cge {if _afda ==_gag {_daf =false ;break ;};};if _daf {if _bdde :=_aedg .addLayoutFromSlide (s );_bdde !=nil {return Slide {},_bdde ;};};_aedg ._ggcc =append (_aedg ._ggcc ,s ._fea );_aedg ._ege =append (_aedg ._ege ,len (_aedg ._ggcc ));
_afb :=_aedg ._ddcf .AddAutoRelationship (_ge .DocTypePresentation ,_ge .OfficeDocumentType ,len (_aedg ._ggcc ),_ge .SlideType );_cfa .RIdAttr =_afb .ID ();_eef :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .SlideType ,len (_aedg ._ggcc ));_aedg .ContentTypes .AddOverride (_eef ,_ge .SlideContentType );
_bbgc :=_adc .NewRelationships ();_aedg ._bcd =append (_aedg ._bcd ,_bbgc );_fgaa :=len (_aedg ._bcd )-1;for _gce ,_gdf :=range _aedg ._cge {if _gdf ==_gag {_bac :=_aedg ._bdb [_gce ];for _ ,_gcee :=range _bac .X ().Relationship {if _gcee .TypeAttr !=_ge .SlideMasterType {_aedg ._bcd [_fgaa ].X ().Relationship =append (_aedg ._bcd [_fgaa ].X ().Relationship ,_gcee );
};};_bbgc .AddAutoRelationship (_ge .DocTypePresentation ,_ge .SlideType ,_gce +1,_ge .SlideLayoutType );};};_cfaf :=Slide {_cfa ,s ._fea ,_aedg ,nil };return _cfaf ,nil ;};

// X returns TextBox's underlying *pml.CT_Shape.
func (_fbcf TextBox )X ()*_db .CT_Shape {return _fbcf ._gff };const _add float64 =500000;

// X returns the inner wrapped XML type.
func (_ddac *SlideSize )X ()*_db .CT_SlideSize {return _ddac ._bfce };

// AddSlideWithLayout adds a new slide with content copied from a layout.  Normally you should
// use AddDefaultSlideWithLayout as it will do some post processing similar to PowerPoint to
// clear place holder text, etc.
func (_abfe *Presentation )AddSlideWithLayout (l SlideLayout )(Slide ,error ){_afg :=_db .NewCT_SlideIdListEntry ();_afg .IdAttr =_abfe .nextSlideID ();_abfe ._agc .SldIdLst .SldId =append (_abfe ._agc .SldIdLst .SldId ,_afg );_dee :=_db .NewSld ();_gfef :=_dcf .Buffer {};
_baeb :=_ffe .NewEncoder (&_gfef );_adda :=_ffe .StartElement {Name :_ffe .Name {Local :"\u0073\u006c\u0069d\u0065"}};_adda .Attr =append (_adda .Attr ,_ffe .Attr {Name :_ffe .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006f\u0070\u0065\u006e\u0078m\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073\u002eo\u0072\u0067\u002f\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061\u0074\u0069o\u006e\u006d\u006c\u002f\u0032\u00300\u0036\u002f\u006da\u0069\u006e"});
_adda .Attr =append (_adda .Attr ,_ffe .Attr {Name :_ffe .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0061"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065m\u0061\u0073\u002e\u006f\u0070\u0065\u006e\u0078m\u006cf\u006f\u0072\u006d\u0061\u0074\u0073\u002e\u006f\u0072\u0067\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067m\u006c\u002f\u0032\u0030\u0030\u0036\u002f\u006d\u0061\u0069\u006e"});
_adda .Attr =append (_adda .Attr ,_ffe .Attr {Name :_ffe .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0070"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006f\u0070\u0065\u006e\u0078m\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073\u002eo\u0072\u0067\u002f\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061\u0074\u0069o\u006e\u006d\u006c\u002f\u0032\u00300\u0036\u002f\u006da\u0069\u006e"});
_adda .Attr =append (_adda .Attr ,_ffe .Attr {Name :_ffe .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0072"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068\u0065\u006da\u0073\u002e\u006f\u0070\u0065\u006ex\u006d\u006c\u0066\u006f\u0072m\u0061\u0074\u0073\u002e\u006f\u0072\u0067\u002f\u006f\u0066\u0066\u0069c\u0065\u0044\u006f\u0063\u0075\u006d\u0065\u006e\u0074\u002f\u0032\u0030\u0030\u0036\u002fr\u0065\u006c\u0061\u0074\u0069\u006f\u006e\u0073h\u0069\u0070\u0073"});
_adda .Attr =append (_adda .Attr ,_ffe .Attr {Name :_ffe .Name {Local :"\u0078\u006d\u006c\u006e\u0073\u003a\u0073\u0068"},Value :"\u0068\u0074\u0074\u0070\u003a/\u002f\u0073\u0063\u0068\u0065m\u0061s\u002e\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073\u002e\u006f\u0072\u0067/\u006f\u0066\u0066\u0069\u0063\u0065\u0044\u006f\u0063\u0075\u006d\u0065\u006e\u0074\u002f\u0032\u0030\u0030\u0036\u002f\u0073\u0068\u0061\u0072e\u0064\u0054\u0079\u0070\u0065\u0073"});
_adda .Attr =append (_adda .Attr ,_ffe .Attr {Name :_ffe .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
if _cgf :=l ._fcea .CSld .MarshalXML (_baeb ,_adda );_cgf !=nil {return Slide {},_cgf ;};if _ebc :=_baeb .Flush ();_ebc !=nil {return Slide {},_ebc ;};_bcgc :=_ffe .NewDecoder (&_gfef );_dee .CSld =_db .NewCT_CommonSlideData ();if _dga :=_bcgc .Decode (_dee .CSld );
_dga !=nil {return Slide {},_dga ;};_dee .CSld .NameAttr =nil ;_dee .CSld .SpTree .GroupShapeChoice =_gbg (_dee .CSld .SpTree .GroupShapeChoice );_afaa :=make ([]*_db .CT_GroupShapeChoice ,0);for _ ,_fgca :=range _dee .CSld .SpTree .GroupShapeChoice {if _cea :=_fgca .Sp ;
_cea !=nil {if _egf :=_cea .NvSpPr ;_egf !=nil {if _ccab :=_egf .NvPr ;_ccab !=nil {if _cfc :=_ccab .Ph ;_cfc !=nil {_afaa =append (_afaa ,_fgca );};};};};};_dee .CSld .SpTree .GroupShapeChoice =_afaa ;_abfe ._ggcc =append (_abfe ._ggcc ,_dee );_abfe ._ege =append (_abfe ._ege ,len (_abfe ._ggcc ));
_bda :=_abfe ._ddcf .AddAutoRelationship (_ge .DocTypePresentation ,_ge .OfficeDocumentType ,len (_abfe ._ggcc ),_ge .SlideType );_afg .RIdAttr =_bda .ID ();_agef :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .SlideType ,len (_abfe ._ggcc ));_abfe .ContentTypes .AddOverride (_agef ,_ge .SlideContentType );
_egc :=_adc .NewRelationships ();_abfe ._bcd =append (_abfe ._bcd ,_egc );_dddb :=len (_abfe ._bcd )-1;for _dgbd ,_ggg :=range _abfe ._cge {if _ggg ==l .X (){_ffb :=_abfe ._bdb [_dgbd ];for _ ,_ebfg :=range _ffb .X ().Relationship {if _ebfg .TypeAttr !=_ge .SlideMasterType {_abfe ._bcd [_dddb ].X ().Relationship =append (_abfe ._bcd [_dddb ].X ().Relationship ,_ebfg );
};};_egc .AddAutoRelationship (_ge .DocTypePresentation ,_ge .SlideType ,_dgbd +1,_ge .SlideLayoutType );};};_ceea :=Slide {_afg ,_dee ,_abfe ,nil };return _ceea ,nil ;};

// NewSlideScreenSizeWithValue returns slide screen size with given width and height.
// Width and Height value is in EMU units, use our measurement.ToEMU to convert the -
// width and height value.
func NewSlideScreenSizeWithValue (width ,height int32 )SlideScreenSize {return SlideScreenSize {width ,height };};

// Width returns slide screen size width in EMU units.
func (_gdcg *SlideScreenSize )Width ()int32 {return _gdcg [0]};func _dca (_df *Presentation ,_fb *_db .CT_Shape ,_ceg *_db .CT_GraphicalObjectFrame ,_ged *TableInfo ,_aaf *_ag .CT_Transform2D ,_bcfc int ,_dbc []rectangle ,_da []*_ag .CT_TextParagraph )[]*TextItem {_fbd :=[]*TextItem {};
var _cg ,_acc ,_bae ,_bfc ,_aec ,_ded int64 ;_gbd :=_aaf ==nil ;_ddc :=0;for _ ,_fa :=range _da {for _ ,_ca :=range _fa .EG_TextRun {if _bbe :=_ca .TextRunChoice .R ;_bbe !=nil {if !_gbd {if _aaf .Off !=nil {if _gab :=_aaf .Ext ;_gab !=nil {_aec ,_ded =_gab .CxAttr ,_gab .CyAttr ;
};if _fdd :=_aaf .Off .XAttr .ST_CoordinateUnqualified ;_fdd !=nil {_cg =*_fdd ;_acc =_cg +_aec ;_gbd =true ;};if _ccac :=_aaf .Off .YAttr .ST_CoordinateUnqualified ;_ccac !=nil {_bae =*_ccac ;_bfc =_bae +_ded ;_gbd =true ;};};};_deg :=append ([]rectangle {},_dbc ...);
_deg =append (_deg ,rectangle {_c :_cg ,_efbf :_acc ,_cc :_bae ,_cca :_bfc });_fbd =append (_fbd ,&TextItem {Presentation :_df ,Shape :_fb ,GraphicFrame :_ceg ,TableInfo :_ged ,Paragraph :_fa ,Run :_bbe ,Text :_bbe .T ,_bc :_deg ,_fg :_bcfc ,_afa :_ddc });
_ddc ++;};};};return _fbd ;};

// GetPlaceholderByIndex returns a placeholder given its index.  If there are multiplace
// placeholders of the same index, this method returns the first one.  You must use the
// PlaceHolders() method to access the others.
func (_cfggb Slide )GetPlaceholderByIndex (idx uint32 )(PlaceHolder ,error ){for _ ,_eddb :=range _cfggb ._fea .CSld .SpTree .GroupShapeChoice {if _eddb .Sp !=nil &&_eddb .Sp .NvSpPr !=nil &&_eddb .Sp .NvSpPr .NvPr !=nil &&_eddb .Sp .NvSpPr .NvPr .Ph !=nil {if (idx ==0&&_eddb .Sp .NvSpPr .NvPr .Ph .IdxAttr ==nil )||(_eddb .Sp .NvSpPr .NvPr .Ph .IdxAttr !=nil &&*_eddb .Sp .NvSpPr .NvPr .Ph .IdxAttr ==idx ){return PlaceHolder {_eddb .Sp ,_cfggb ._fea },nil ;
};};};return PlaceHolder {},_ab .New ("\u0075\u006e\u0061\u0062\u006c\u0065\u0020\u0074\u006f\u0020\u0066i\u006e\u0064\u0020\u0070\u006c\u0061\u0063\u0065\u0068\u006fl\u0064\u0065\u0072");};

// Type returns the placeholder type
func (_gbf PlaceHolder )Type ()_db .ST_PlaceholderType {return _gbf ._abfg .NvSpPr .NvPr .Ph .TypeAttr };

// SlideSize represents a slide size of a presentation.
type SlideSize struct{_bfce *_db .CT_SlideSize ;_dbbe *Presentation ;};func (_gc *chart )Target ()string {return _gc ._aab };

// Images returns the images referenced by the slide, in relationship order.
// Images that come only from the slide layout or master are not included.
func (_ebgab *Slide )Images ()[]_adc .ImageRef {_cbbb :=_ebgab .getSlideRels ();if (_cbbb ==_adc .Relationships {}){return nil ;};var _edbf []_adc .ImageRef ;for _ ,_addb :=range _cbbb .Relationships (){if _addb .Type ()!=_ge .ImageType {continue ;};for _ ,_beddg :=range _ebgab ._agab .Images {if _beddg .Target ()==_addb .Target (){_edbf =append (_edbf ,_beddg );
break ;};};};return _edbf ;};

// Slides returns the slides in the presentation.
func (_ede *Presentation )Slides ()[]Slide {_bgaa :=[]Slide {};for _afge ,_adgc :=range _ede ._ggcc {var _cgfb *_db .CT_SlideIdListEntry ;if _ede ._agc .SldIdLst !=nil &&_afge < len (_ede ._agc .SldIdLst .SldId ){_cgfb =_ede ._agc .SldIdLst .SldId [_afge ];
};_bgaa =append (_bgaa ,Slide {_cgfb ,_adgc ,_ede ,nil });};return _bgaa ;};

// Index returns the placeholder index
func (_ebg PlaceHolder )Index ()uint32 {if _ebg ._abfg .NvSpPr .NvPr .Ph .IdxAttr ==nil {return 0;};return *_ebg ._abfg .NvSpPr .NvPr .Ph .IdxAttr ;};

// NormalViewPr returns the NormalViewPr property.
func (_acdd ViewProperties )NormalViewPr ()*_db .CT_NormalViewProperties {return _acdd ._dgeb .NormalViewPr ;};

// SlideText is an array of extracted text items which has some methods for representing extracted text from a slide.
type SlideText struct{Items []*TextItem ;};

// ExtractText returns text from a slide as a SlideText object.
func (_ce *Slide )ExtractText ()*SlideText {_bd :=_ade (_ce ._agab ,_ce ._fea .CSld .SpTree .GroupShapeChoice ,[]rectangle {},[]*TextItem {});_ac .Sort (sort2d (_bd ));return &SlideText {Items :_bd };};

// SaveToFileAsTemplate writes the Presentation out to a file as a template.
func (_fe *Presentation )SaveToFileAsTemplate (path string )error {return _fe .saveToFile (path ,true )};

// RemoveSlide removes a slide from a presentation.
func (_bafc *Presentation )RemoveSlide (s Slide )error {_abaa :=false ;_fafa :=0;for _egaf ,_ecfb :=range _bafc ._ggcc {if _ecfb ==s ._fea {_aabc :=_bafc ._agc .SldIdLst !=nil &&_egaf < len (_bafc ._agc .SldIdLst .SldId );if _aabc {if _bafc ._agc .SldIdLst .SldId [_egaf ]!=s ._cddgg {return _ab .New ("i\u006e\u0063\u006f\u006e\u0073\u0069s\u0074\u0065\u006e\u0063\u0079\u0020i\u006e\u0020\u0073\u006c\u0069\u0064\u0065s\u0020\u0061\u006e\u0064\u0020\u0049\u0044\u0020\u006c\u0069s\u0074");
};}else if s ._cddgg !=nil {return _ab .New ("i\u006e\u0063\u006f\u006e\u0073\u0069s\u0074\u0065\u006e\u0063\u0079\u0020i\u006e\u0020\u0073\u006c\u0069\u0064\u0065s\u0020\u0061\u006e\u0064\u0020\u0049\u0044\u0020\u006c\u0069s\u0074");};copy (_bafc ._ggcc [_egaf :],_bafc ._ggcc [_egaf +1:]);
_bafc ._ggcc =_bafc ._ggcc [0:len (_bafc ._ggcc )-1];copy (_bafc ._bcd [_egaf :],_bafc ._bcd [_egaf +1:]);_bafc ._bcd =_bafc ._bcd [0:len (_bafc ._bcd )-1];if _aabc {copy (_bafc ._agc .SldIdLst .SldId [_egaf :],_bafc ._agc .SldIdLst .SldId [_egaf +1:]);
_bafc ._agc .SldIdLst .SldId =_bafc ._agc .SldIdLst .SldId [0:len (_bafc ._agc .SldIdLst .SldId )-1];};copy (_bafc ._ege [_egaf :],_bafc ._ege [_egaf +1:]);_bafc ._ege =_bafc ._ege [0:len (_bafc ._ege )-1];_abaa =true ;_fafa =_egaf ;};};if !_abaa {return _ab .New ("u\u006ea\u0062\u006c\u0065\u0020\u0074\u006f\u0020\u0066i\u006e\u0064\u0020\u0073li\u0064\u0065");
};_afbc :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .SlideType ,0);return _bafc .ContentTypes .RemoveOverrideByIndex (_afbc ,_fafa );};

// SlideSize returns presentation slide size.
func (_cfgg *Presentation )SlideSize ()SlideSize {if _cfgg ._agc .SldSz ==nil {_cfgg ._agc .SldSz =_db .NewCT_SlideSize ();};return SlideSize {_cfgg ._agc .SldSz ,_cfgg };};func _gbg (_bfe []*_db .CT_GroupShapeChoice )[]*_db .CT_GroupShapeChoice {var _ecc []*_db .CT_GroupShapeChoice ;
for _ ,_bab :=range _bfe {if _bab .Pic ==nil {_ecc =append (_ecc ,_bab );};};return _ecc ;};func (_abe *Presentation )addLayoutFromSlide (_baed Slide )error {_dgbb :=1;for _ ,_agcg :=range _abe .Images {if _fab ,_bbge :=_ff .StringToNumbers (_agcg .Target ());
_bbge &&_fab >=_dgbb {_dgbb =_fab +1;};};_abe ._cge =append (_abe ._cge ,_baed .GetSlideLayout ());_aded :=_baed .getSlideLayoutRels ();for _ ,_fda :=range _aded .X ().Relationship {if _fda .TypeAttr ==_ge .ImageType {_cae ,_caeb :=_baed ._agab .GetImageByTarget (_fda .TargetAttr );
if _caeb {if _cfd ,_fdgc :=_ff .StringToNumbers (_cae .Target ());_fdgc &&_cfd < _dgbb {_cae .SetTarget (_b .ReplaceAll (_cae .Target (),_dc .Sprint (_cfd ),_dc .Sprint (_dgbb )));_fda .TargetAttr =_cae .Target ();_dgbb =_dgbb +1;};_abe .Images =append (_abe .Images ,_cae );
};};};_abe ._bdb =append (_abe ._bdb ,_aded );if len (_abe ._dfdb )> 0&&len (_abe ._bcg )> 0{_fcg :=_abe ._bcg [0].AddAutoRelationship (_ge .DocTypePresentation ,_ge .SlideMasterType ,len (_abe ._cge ),_ge .SlideLayoutType );_abe ._bcg [0].Reorder ();_bfa :=_db .NewCT_SlideLayoutIdListEntry ();
_bfa .IdAttr =_ge .Uint32 (2147483649);_bfa .RIdAttr =_fcg .ID ();for _ ,_dde :=range _abe ._dfdb [0].SldLayoutIdLst .SldLayoutId {if *_dde .IdAttr >=*_bfa .IdAttr {_bfa .IdAttr =_ge .Uint32 ((*_dde .IdAttr +2));};};_abe ._dfdb [0].SldLayoutIdLst .SldLayoutId =append (_abe ._dfdb [0].SldLayoutIdLst .SldLayoutId ,_bfa );
};_fdcg :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .SlideLayoutType ,len (_abe ._cge ));_abe .ContentTypes .AddOverride (_fdcg ,_ge .SlideLayoutContentType );return nil ;};

// Themes returns an array of presentation themes.
func (_bgd *Presentation )Themes ()[]*_ag .Theme {return _bgd ._gfd };

// WebPr returns the WebPr property.
func (_bcaf PresentationProperties )WebPr ()*_db .CT_WebProperties {return _bcaf ._gbdc .WebPr };

// SlideLayouts returns a slice of all layouts in SlideMaster.
func (_gedb SlideMaster )SlideLayouts ()[]SlideLayout {_aee :=map[string ]int {};_fdag :=[]SlideLayout {};for _ ,_dbfa :=range _gedb ._dcec .Relationships (){_ffee :=_b .Replace (_dbfa .Target (),".\u002e\u002f\u0073\u006c\u0069\u0064e\u004c\u0061\u0079\u006f\u0075\u0074\u0073\u002f\u0073l\u0069\u0064\u0065L\u0061y\u006f\u0075\u0074","",-1);
_ffee =_b .Replace (_ffee ,"\u002e\u0078\u006d\u006c","",-1);if _abde ,_ageg :=_e .ParseInt (_ffee ,10,32);_ageg ==nil {_aee [_dbfa .ID ()]=int (_abde );};};for _ ,_cec :=range _gedb ._dec .SldLayoutIdLst .SldLayoutId {if _dgef ,_fbbe :=_aee [_cec .RIdAttr ];
_fbbe {_acg :=_gedb ._dfb ._cge [_dgef -1];_fdag =append (_fdag ,SlideLayout {_acg });};};return _fdag ;};

// OpenTemplate opens a template file.
func OpenTemplate (fn string )(*Presentation ,error ){_gaa ,_fdf :=Open (fn );if _fdf !=nil {return nil ,_fdf ;};return _gaa ,nil ;};

// GetColorBySchemeColor returns *dml.CT_Color mapped to scheme colors like dk1, lt1 etc. depending on what theme is used in the presentation.
func (_dag *Presentation )GetColorBySchemeColor (schClr _ag .ST_SchemeColorVal )*_ag .CT_Color {if len (_dag ._dfdb )==0||len (_dag ._gfd )==0{return nil ;};var _dgfa _ag .ST_ColorSchemeIndex ;_cdcga :=_dag ._dfdb [0];_ada :=_cdcga .ClrMap ;switch schClr .String (){case "\u0062\u0067\u0031":_dgfa =_ada .Bg1Attr ;
case "\u0062\u0067\u0032":_dgfa =_ada .Bg2Attr ;case "\u0074\u0078\u0031":_dgfa =_ada .Tx1Attr ;case "\u0074\u0078\u0032":_dgfa =_ada .Tx2Attr ;case "\u0061c\u0063\u0065\u006e\u0074\u0031":_dgfa =_ada .Accent1Attr ;case "\u0061c\u0063\u0065\u006e\u0074\u0032":_dgfa =_ada .Accent2Attr ;
case "\u0061c\u0063\u0065\u006e\u0074\u0033":_dgfa =_ada .Accent3Attr ;case "\u0061c\u0063\u0065\u006e\u0074\u0034":_dgfa =_ada .Accent4Attr ;case "\u0061c\u0063\u0065\u006e\u0074\u0035":_dgfa =_ada .Accent5Attr ;case "\u0061c\u0063\u0065\u006e\u0074\u0036":_dgfa =_ada .Accent6Attr ;
case "\u0068\u006c\u0069n\u006b":_dgfa =_ada .HlinkAttr ;case "\u0066\u006f\u006c\u0048\u006c\u0069\u006e\u006b":_dgfa =_ada .FolHlinkAttr ;case "\u0064\u006b\u0031":_dgfa =_ag .ST_ColorSchemeIndexDk1 ;case "\u0064\u006b\u0032":_dgfa =_ag .ST_ColorSchemeIndexDk2 ;
case "\u006c\u0074\u0031":_dgfa =_ag .ST_ColorSchemeIndexLt1 ;case "\u006c\u0074\u0032":_dgfa =_ag .ST_ColorSchemeIndexLt2 ;default:_dgfa =_ag .ST_ColorSchemeIndexUnset ;};_dgfg :=_dag ._gfd [0];_gcfc :=_dgfg .ThemeElements ;if _gcfc ==nil {return nil ;
};var _gecb *_ag .CT_Color ;_dcae :=_gcfc .ClrScheme ;switch _dgfa .String (){case "\u0064\u006b\u0031":_gecb =_dcae .Dk1 ;case "\u0064\u006b\u0032":_gecb =_dcae .Dk2 ;case "\u006c\u0074\u0031":_gecb =_dcae .Lt1 ;case "\u006c\u0074\u0032":_gecb =_dcae .Lt2 ;
case "\u0061c\u0063\u0065\u006e\u0074\u0031":_gecb =_dcae .Accent1 ;case "\u0061c\u0063\u0065\u006e\u0074\u0032":_gecb =_dcae .Accent2 ;case "\u0061c\u0063\u0065\u006e\u0074\u0033":_gecb =_dcae .Accent3 ;case "\u0061c\u0063\u0065\u006e\u0074\u0034":_gecb =_dcae .Accent4 ;
case "\u0061c\u0063\u0065\u006e\u0074\u0035":_gecb =_dcae .Accent5 ;case "\u0061c\u0063\u0065\u006e\u0074\u0036":_gecb =_dcae .Accent6 ;case "\u0068\u006c\u0069n\u006b":_gecb =_dcae .Hlink ;case "\u0066\u006f\u006c\u0048\u006c\u0069\u006e\u006b":_gecb =_dcae .FolHlink ;
default:return nil ;};return _gecb ;};

// NewPresentationProperties constructs a new PresentationProperties.
func NewPresentationProperties ()PresentationProperties {return PresentationProperties {_gbdc :_db .NewPresentationPr ()};};

// Paragraphs returns the paragraphs defined in the placeholder.
func (_ebga PlaceHolder )Paragraphs ()[]_be .Paragraph {_cfg :=[]_be .Paragraph {};for _ ,_fdff :=range _ebga ._abfg .TxBody .P {_cfg =append (_cfg ,_be .MakeParagraph (_fdff ));};return _cfg ;};

// PlaceHolders returns all of the content place holders within a given slide.
func (_aaga Slide )PlaceHolders ()[]PlaceHolder {_bfd :=[]PlaceHolder {};for _ ,_bcgcc :=range _aaga ._fea .CSld .SpTree .GroupShapeChoice {if _bcgcc .Sp !=nil &&_bcgcc .Sp .NvSpPr !=nil &&_bcgcc .Sp .NvSpPr .NvPr !=nil &&_bcgcc .Sp .NvSpPr .NvPr .Ph !=nil {_bfd =append (_bfd ,PlaceHolder {_bcgcc .Sp ,_aaga ._fea });
};};return _bfd ;};

// ShowPr returns the ShowPr property.
func (_addg PresentationProperties )ShowPr ()*_db .CT_ShowProperties {return _addg ._gbdc .ShowPr };

// Close closes the presentation, removing any temporary files that might have been
// created when opening a document.
func (_bdge *Presentation )Close ()error {if _bdge .TmpPath !=""{return _ad .RemoveAll (_bdge .TmpPath );};return nil ;};func (_cff *Presentation )save (_cga _fd .Writer ,_dafc bool )error {const _gaaa ="\u0050\u0072\u0065\u0073en\u0074\u0061\u0074\u0069\u006f\u006e\u003a\u0070\u002e\u0053\u0061\u0076\u0065";
if _cffg :=_cff ._agc .Validate ();_cffg !=nil {_dd .Log .Debug ("\u0076\u0061\u006c\u0069\u0064\u0061\u0074\u0069\u006f\u006e\u0020\u0065\u0072\u0072\u006fr\u0020i\u006e\u0020\u0064\u006f\u0063\u0075\u006d\u0065\u006e\u0074\u003a\u0020\u0025\u0073",_cffg );
};if !_ef .GetLicenseKey ().IsLicensed ()&&!_gcf {_dc .Println ("\u0055\u006e\u006ci\u0063\u0065\u006e\u0073e\u0064\u0020\u0076\u0065\u0072\u0073\u0069o\u006e\u0020\u006f\u0066\u0020\u0055\u006e\u0069\u004f\u0066\u0066\u0069\u0063\u0065");_dc .Println ("\u002d\u0020\u0047e\u0074\u0020\u0061\u0020\u0074\u0072\u0069\u0061\u006c\u0020\u006c\u0069\u0063\u0065\u006e\u0073\u0065\u0020\u006f\u006e\u0020\u0068\u0074\u0074\u0070\u0073\u003a\u002f\u002fu\u006e\u0069\u0064\u006f\u0063\u002e\u0069\u006f");
return _ab .New ("\u0075\u006e\u0069\u006f\u0066\u0066\u0069\u0063\u0065\u0020\u006ci\u0063\u0065\u006e\u0073\u0065\u0020\u0072\u0065\u0071\u0075i\u0072\u0065\u0064");};_egdf :="\u0075n\u006b\u006e\u006f\u0077\u006e";if _egfd ,_edd :=_cga .(*_eg .File );
_edd {_egdf =_egfd .Name ();};if len (_cff ._bddf )==0{_dbcg ,_egef :=_ef .GenRefId ("\u0070\u0077");if _egef !=nil {_dd .Log .Error ("\u0045R\u0052\u004f\u0052\u003a\u0020\u0025v",_egef );return _egef ;};_cff ._bddf =_dbcg ;};if _dcc :=_ef .Track (_cff ._bddf ,_gaaa ,_egdf );
_dcc !=nil {_dd .Log .Error ("\u0045R\u0052\u004f\u0052\u003a\u0020\u0025v",_dcc );return _dcc ;};if _dafc {_cff .ContentTypes .RemoveOverride ("\u0061\u0070\u0070\u006c\u0069\u0063\u0061t\u0069\u006f\u006e\u002f\u0076\u006e\u0064\u002e\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072m\u0061\u0074\u0073\u002d\u006ff\u0066\u0069\u0063\u0065\u0064\u006f\u0063\u0075\u006de\u006e\u0074\u002e\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061\u0074\u0069\u006f\u006e\u006d\u006c\u002e\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061\u0074\u0069\u006f\u006e\u002e\u006d\u0061\u0069\u006e\u002b\u0078\u006d\u006c");
_cff .ContentTypes .EnsureOverride ("/\u0070\u0070\u0074\u002fpr\u0065s\u0065\u006e\u0074\u0061\u0074i\u006f\u006e\u002e\u0078\u006d\u006c","\u0061\u0070pl\u0069\u0063\u0061\u0074\u0069\u006f\u006e\u002f\u0076\u006e\u0064\u002e\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066o\u0072\u006d\u0061\u0074s\u002d\u006f\u0066\u0066ic\u0065\u0064o\u0063u\u006d\u0065\u006e\u0074\u002e\u0070r\u0065\u0073\u0065n\u0074\u0061t\u0069\u006f\u006e\u006d\u006c\u002e\u0074\u0065\u006d\u0070\u006c\u0061\u0074\u0065.\u006d\u0061\u0069\u006e\u002b\u0078\u006d\u006c");
}else {_cff .ContentTypes .RemoveOverride ("\u0061\u0070pl\u0069\u0063\u0061\u0074\u0069\u006f\u006e\u002f\u0076\u006e\u0064\u002e\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066o\u0072\u006d\u0061\u0074s\u002d\u006f\u0066\u0066ic\u0065\u0064o\u0063u\u006d\u0065\u006e\u0074\u002e\u0070r\u0065\u0073\u0065n\u0074\u0061t\u0069\u006f\u006e\u006d\u006c\u002e\u0074\u0065\u006d\u0070\u006c\u0061\u0074\u0065.\u006d\u0061\u0069\u006e\u002b\u0078\u006d\u006c");
_cff .ContentTypes .EnsureOverride ("/\u0070\u0070\u0074\u002fpr\u0065s\u0065\u006e\u0074\u0061\u0074i\u006f\u006e\u002e\u0078\u006d\u006c","\u0061\u0070\u0070\u006c\u0069\u0063\u0061t\u0069\u006f\u006e\u002f\u0076\u006e\u0064\u002e\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072m\u0061\u0074\u0073\u002d\u006ff\u0066\u0069\u0063\u0065\u0064\u006f\u0063\u0075\u006de\u006e\u0074\u002e\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061\u0074\u0069\u006f\u006e\u006d\u006c\u002e\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061\u0074\u0069\u006f\u006e\u002e\u006d\u0061\u0069\u006e\u002b\u0078\u006d\u006c");
};_fbb :=_ge .DocTypePresentation ;_abff :=_gg .NewWriter (_cga );defer func (){if _cbb :=_abff .Close ();_cbb !=nil {_dd .Log .Error ("\u0045R\u0052\u004f\u0052\u003a\u0020\u0025v",_cbb );};}();if _fdda :=_a .MarshalXML (_abff ,_ge .BaseRelsFilename ,_cff .Rels .X ());
_fdda !=nil {return _fdda ;};if _caf :=_a .MarshalXMLByType (_abff ,_fbb ,_ge .ExtendedPropertiesType ,_cff .AppProperties .X ());_caf !=nil {return _caf ;};if _ecf :=_a .MarshalXMLByType (_abff ,_fbb ,_ge .CorePropertiesType ,_cff .CoreProperties .X ());
_ecf !=nil {return _ecf ;};if _eefd :=_a .MarshalXMLByType (_abff ,_fbb ,_ge .PresentationPropertiesType ,_cff ._dcd .X ());_eefd !=nil {return _eefd ;};if _cbgd :=_a .MarshalXMLByType (_abff ,_fbb ,_ge .ViewPropertiesType ,_cff ._cdad .X ());_cbgd !=nil {return _cbgd ;
};if _baf :=_a .MarshalXMLByType (_abff ,_fbb ,_ge .TableStylesType ,_cff ._eda .X ());_baf !=nil {return _baf ;};if len (_cff ._cdeg )> 0{for _adf ,_aad :=range _cff ._cdeg {_fbcb :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .CustomXMLType ,_cff ._aafa [_adf ]);
if _dccg :=_a .MarshalXML (_abff ,_fbcb ,_aad );_dccg !=nil {return _dccg ;};};};if _cff .CustomProperties .X ()!=nil {if _deaa :=_a .MarshalXMLByType (_abff ,_fbb ,_ge .CustomPropertiesType ,_cff .CustomProperties .X ());_deaa !=nil {return _deaa ;};};
if _cff .Thumbnail !=nil {_ggad ,_fadd :=_abff .Create ("\u0064\u006f\u0063Pr\u006f\u0070\u0073\u002f\u0074\u0068\u0075\u006d\u0062\u006e\u0061\u0069\u006c\u002e\u006a\u0070\u0065\u0067");if _fadd !=nil {return _fadd ;};if _ddbd :=_efd .Encode (_ggad ,_cff .Thumbnail ,nil );
_ddbd !=nil {return _ddbd ;};};_ccc :=_ge .AbsoluteFilename (_fbb ,_ge .OfficeDocumentType ,0);if _fdfc :=_a .MarshalXML (_abff ,_ccc ,_cff ._agc );_fdfc !=nil {return _fdfc ;};if _gaaf :=_a .MarshalXML (_abff ,_a .RelationsPathFor (_ccc ),_cff ._ddcf .X ());
_gaaf !=nil {return _gaaf ;};for _cgeb ,_cef :=range _cff ._ggcc {if _cef ==nil {continue ;};_bfg :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .SlideType ,_cff ._ege [_cgeb ]);if _efgc :=_a .MarshalXML (_abff ,_bfg ,_cef );_efgc !=nil {return _efgc ;
};if !_cff ._bcd [_cgeb ].IsEmpty (){_acd :=_a .RelationsPathFor (_bfg );if _ccd :=_a .MarshalXML (_abff ,_acd ,_cff ._bcd [_cgeb ].X ());_ccd !=nil {return _ccd ;};};};for _eaf ,_edfg :=range _cff ._dfdb {if _edfg ==nil {continue ;};_cdd :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .SlideMasterType ,_cff ._dbb [_eaf ]);
if _ccdb :=_a .MarshalXML (_abff ,_cdd ,_edfg );_ccdb !=nil {return _ccdb ;};if !_cff ._bcg [_eaf ].IsEmpty (){_dcga :=_a .RelationsPathFor (_cdd );if _bafa :=_a .MarshalXML (_abff ,_dcga ,_cff ._bcg [_eaf ].X ());_bafa !=nil {return _bafa ;};};};for _fcb ,_gcfd :=range _cff ._cge {if _gcfd ==nil {continue ;
};_bde :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .SlideLayoutType ,_fcb +1);if _fadf :=_a .MarshalXML (_abff ,_bde ,_gcfd );_fadf !=nil {return _fadf ;};if !_cff ._bdb [_fcb ].IsEmpty (){_dcb :=_a .RelationsPathFor (_bde );if _bfee :=_a .MarshalXML (_abff ,_dcb ,_cff ._bdb [_fcb ].X ());
_bfee !=nil {return _bfee ;};};};for _eaec ,_bggg :=range _cff ._gfd {if _bggg ==nil {continue ;};_efdg :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .ThemeType ,_cff ._fbc [_eaec ]);if _gad :=_a .MarshalXML (_abff ,_efdg ,_bggg );_gad !=nil {return _gad ;
};if !_cff ._gbfbc [_eaec ].IsEmpty (){_bea :=_a .RelationsPathFor (_efdg );if _agec :=_a .MarshalXML (_abff ,_bea ,_cff ._gbfbc [_eaec ].X ());_agec !=nil {return _agec ;};};};for _bbgf ,_dgf :=range _cff ._efa {_aac :=_ge .AbsoluteFilename (_fbb ,_ge .ChartType ,_bbgf +1);
if _gge :=_a .MarshalXML (_abff ,_aac ,_dgf .X ());_gge !=nil {return _gge ;};};for _cfdg ,_fgcab :=range _cff ._beb {_fgbc :=_ge .AbsoluteFilename (_fbb ,_ge .HandoutMasterType ,_cfdg +1);if _ffda :=_a .MarshalXML (_abff ,_fgbc ,_fgcab );_ffda !=nil {return _ffda ;
};};for _aef ,_ecca :=range _cff ._cce {if _ecca ==nil {continue ;};_eacg :=_ge .AbsoluteFilename (_fbb ,_ge .NotesMasterType ,_cff ._ffd [_aef ]);if _dbbf :=_a .MarshalXML (_abff ,_eacg ,_ecca );_dbbf !=nil {return _dbbf ;};};for _egad ,_gef :=range _cff .Images {_cefa :=_egad +1;
if _geee ,_bec :=_ff .StringToNumbers (_gef .Target ());_bec &&_cefa !=_geee {_cefa =_geee ;};if _caad :=_adc .AddImageToZip (_abff ,_gef ,_cefa ,_ge .DocTypePresentation );_caad !=nil {return _caad ;};};_cff .ContentTypes .EnsureDefault ("\u0070\u006e\u0067","\u0069m\u0061\u0067\u0065\u002f\u0070\u006eg");
_cff .ContentTypes .EnsureDefault ("\u006a\u0070\u0065\u0067","\u0069\u006d\u0061\u0067\u0065\u002f\u006a\u0070\u0065\u0067");_cff .ContentTypes .EnsureDefault ("\u006a\u0070\u0067","\u0069\u006d\u0061\u0067\u0065\u002f\u006a\u0070\u0065\u0067");_cff .ContentTypes .EnsureDefault ("\u0077\u006d\u0066","i\u006d\u0061\u0067\u0065\u002f\u0078\u002d\u0077\u006d\u0066");
if _bddc :=_a .MarshalXML (_abff ,_ge .ContentTypesFilename ,_cff .ContentTypes .X ());_bddc !=nil {return _bddc ;};if _dafb :=_cff .WriteExtraFiles (_abff );_dafb !=nil {return _dafb ;};return nil ;};func (_ccaa *Slide )getSlideLayoutRels ()_adc .Relationships {_edea :=_ccaa ._agab ;
for _aacd ,_feb :=range _edea .SlideLayouts (){if *_ccaa .GetSlideLayout ().CSld ==*_feb ._fcea .CSld {return _edea ._bdb [_aacd ];};};return _adc .Relationships {};};

// GetTableStyleById returns *dml.CT_TableStyle by its style id.
func (_adab *Presentation )GetTableStyleById (id string )*_ag .CT_TableStyle {_dae :=_adab ._eda .TblStyle ();for _ ,_ceb :=range _dae {if _ceb .StyleIdAttr ==id {return _ceb ;};};return nil ;};

// Text returns text from a presentation as one string separated with line breaks.
func (_gedc *PresentationText )Text ()string {_ec :=_dcf .NewBuffer ([]byte {});for _ ,_daa :=range _gedc .Slides {_ec .WriteString (_daa .Text ());};return _ec .String ();};

// TextItem is used for keeping text with references to a paragraph and run, a shape or a table, a row and a cell where it is located.
type TextItem struct{Text string ;Presentation *Presentation ;Shape *_db .CT_Shape ;GraphicFrame *_db .CT_GraphicalObjectFrame ;Paragraph *_ag .CT_TextParagraph ;Run *_ag .CT_RegularTextRun ;TableInfo *TableInfo ;_bc []rectangle ;_fg int ;_afa int ;};

// Presentation returns a slide's presentation.
func (_agf Slide )Presentation ()*Presentation {return _agf ._agab };

// GetColorBySchemeColor returns *dml.CT_Color mapped to scheme colors like dk1, lt1 etc. depending on what theme is used in the presentation.
func (_gedg *Slide )GetColorBySchemeColor (schClr _ag .ST_SchemeColorVal )*_ag .CT_Color {_gedg .ensureClrMap ();_bacc :=_gedg ._dgg ;if _bacc ==nil {return nil ;};var _gegf _ag .ST_ColorSchemeIndex ;switch schClr .String (){case "\u0062\u0067\u0031":_gegf =_bacc .Bg1Attr ;
case "\u0062\u0067\u0032":_gegf =_bacc .Bg2Attr ;case "\u0074\u0078\u0031":_gegf =_bacc .Tx1Attr ;case "\u0074\u0078\u0032":_gegf =_bacc .Tx2Attr ;case "\u0061c\u0063\u0065\u006e\u0074\u0031":_gegf =_bacc .Accent1Attr ;case "\u0061c\u0063\u0065\u006e\u0074\u0032":_gegf =_bacc .Accent2Attr ;
case "\u0061c\u0063\u0065\u006e\u0074\u0033":_gegf =_bacc .Accent3Attr ;case "\u0061c\u0063\u0065\u006e\u0074\u0034":_gegf =_bacc .Accent4Attr ;case "\u0061c\u0063\u0065\u006e\u0074\u0035":_gegf =_bacc .Accent5Attr ;case "\u0061c\u0063\u0065\u006e\u0074\u0036":_gegf =_bacc .Accent6Attr ;
case "\u0068\u006c\u0069n\u006b":_gegf =_bacc .HlinkAttr ;case "\u0066\u006f\u006c\u0048\u006c\u0069\u006e\u006b":_gegf =_bacc .FolHlinkAttr ;case "\u0064\u006b\u0031":_gegf =_ag .ST_ColorSchemeIndexDk1 ;case "\u0064\u006b\u0032":_gegf =_ag .ST_ColorSchemeIndexDk2 ;
case "\u006c\u0074\u0031":_gegf =_ag .ST_ColorSchemeIndexLt1 ;case "\u006c\u0074\u0032":_gegf =_ag .ST_ColorSchemeIndexLt2 ;default:_gegf =_ag .ST_ColorSchemeIndexUnset ;};_ecaac :=_gedg ._agab ._gfd [0];_bba :=_ecaac .ThemeElements ;if _bba ==nil {return nil ;
};var _aabe *_ag .CT_Color ;_edbe :=_bba .ClrScheme ;switch _gegf .String (){case "\u0064\u006b\u0031":_aabe =_edbe .Dk1 ;case "\u0064\u006b\u0032":_aabe =_edbe .Dk2 ;case "\u006c\u0074\u0031":_aabe =_edbe .Lt1 ;case "\u006c\u0074\u0032":_aabe =_edbe .Lt2 ;
case "\u0061c\u0063\u0065\u006e\u0074\u0031":_aabe =_edbe .Accent1 ;case "\u0061c\u0063\u0065\u006e\u0074\u0032":_aabe =_edbe .Accent2 ;case "\u0061c\u0063\u0065\u006e\u0074\u0033":_aabe =_edbe .Accent3 ;case "\u0061c\u0063\u0065\u006e\u0074\u0034":_aabe =_edbe .Accent4 ;
case "\u0061c\u0063\u0065\u006e\u0074\u0035":_aabe =_edbe .Accent5 ;case "\u0061c\u0063\u0065\u006e\u0074\u0036":_aabe =_edbe .Accent6 ;case "\u0068\u006c\u0069n\u006b":_aabe =_edbe .Hlink ;case "\u0066\u006f\u006c\u0048\u006c\u0069\u006e\u006b":_aabe =_edbe .FolHlink ;
default:return nil ;};return _aabe ;};

// SaveAsTemplate writes the presentation out to a writer in the Zip package format as a template
func (_edaa *Presentation )SaveAsTemplate (w _fd .Writer )error {return _edaa .save (w ,true )};func (_gbc *Presentation )onNewRelationship (_cfeb *_a .DecodeMap ,_caaa ,_abee string ,_acf []*_gg .File ,_ecfc *_aa .Relationship ,_ffbc _a .Target )error {_gcb :=_ge .DocTypePresentation ;
switch _abee {case _ge .OfficeDocumentType :_gbc ._agc =_db .NewPresentation ();_cfeb .AddTarget (_caaa ,_gbc ._agc ,_abee ,0);_cfeb .AddTarget (_a .RelationsPathFor (_caaa ),_gbc ._ddcf .X (),_abee ,0);_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,0);
case _ge .CorePropertiesType :_cfeb .AddTarget (_caaa ,_gbc .CoreProperties .X (),_abee ,0);_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,0);case _ge .CustomPropertiesType :_cfeb .AddTarget (_caaa ,_gbc .CustomProperties .X (),_abee ,0);
_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,0);case _ge .PresentationPropertiesType :_cfeb .AddTarget (_caaa ,_gbc ._dcd .X (),_abee ,0);_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,0);case _ge .ViewPropertiesType :_cfeb .AddTarget (_caaa ,_gbc ._cdad .X (),_abee ,0);
_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,0);case _ge .TableStylesType :_cfeb .AddTarget (_caaa ,_gbc ._eda .X (),_abee ,0);_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,0);case _ge .HyperLinkType :_bfaf :=_ag .NewCT_Hyperlink ();
_bbb :=uint32 (len (_gbc ._gfg ));_cfeb .AddTarget (_caaa ,_bfaf ,_abee ,_bbb );_gbc ._gfg =append (_gbc ._gfg ,_bfaf );case _ge .CustomXMLType :if _egfe ,_gca :=_ff .StringToNumbers (_caaa );_gca {if len (_gbc ._cdeg )< _egfe {_ageca :=&_ge .XSDAny {};
_cfeb .AddTarget (_caaa ,_ageca ,_abee ,uint32 (_egfe ));_gbc ._cdeg =append (_gbc ._cdeg ,_ageca );_gbc ._aafa =append (_gbc ._aafa ,_egfe );_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,_egfe );};};case _ge .ChartType :_acfc :=chart {_ga :_g .NewChartSpace ()};
_fdcc :=uint32 (len (_gbc ._efa ));_cfeb .AddTarget (_caaa ,_acfc ._ga ,_abee ,_fdcc );_gbc ._efa =append (_gbc ._efa ,&_acfc );_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,len (_gbc ._efa ));_acfc ._aab =_ecfc .TargetAttr ;case _ge .HandoutMasterType :_gbde :=_db .NewHandoutMaster ();
_aea :=uint32 (len (_gbc ._beb ));_cfeb .AddTarget (_caaa ,_gbde ,_abee ,_aea );_gbc ._beb =append (_gbc ._beb ,_gbde );_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,len (_gbc ._beb ));case _ge .NotesMasterType :if _fba ,_cgb :=_ff .StringToNumbers (_caaa );
_cgb {if len (_gbc ._cce )< _fba {_fca :=_db .NewNotesMaster ();_gbc ._cce =append (_gbc ._cce ,_fca );_gbc ._ffd =append (_gbc ._ffd ,_fba );_cfeb .AddTarget (_caaa ,_fca ,_abee ,uint32 (_fba ));_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,_fba );
};};case _ge .ExtendedPropertiesType :_cfeb .AddTarget (_caaa ,_gbc .AppProperties .X (),_abee ,0);_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,0);case _ge .SlideType :if _agdc ,_gaea :=_ff .StringToNumbers (_caaa );_gaea {if len (_gbc ._ggcc )< _agdc {_fcdc :=_db .NewSld ();
_gbc ._ggcc =append (_gbc ._ggcc ,_fcdc );_gbc ._ege =append (_gbc ._ege ,_agdc );_cfeb .AddTarget (_caaa ,_fcdc ,_abee ,uint32 (_agdc ));_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,_agdc );_fgg :=_adc .NewRelationships ();_cfeb .AddTarget (_a .RelationsPathFor (_caaa ),_fgg .X (),_abee ,0);
if len (_gbc ._bcd )>=_agdc {_gbc ._bcd [_agdc -1]=_fgg ;}else {_gbc ._bcd =append (_gbc ._bcd ,_fgg );};};};case _ge .SlideMasterType :if _bfac ,_deac :=_ff .StringToNumbers (_caaa );_deac {if len (_gbc ._dfdb )< _bfac {_dcgf :=_db .NewSldMaster ();if !_cfeb .AddTarget (_caaa ,_dcgf ,_abee ,uint32 (_bfac )){return nil ;
};_gbc ._dfdb =append (_gbc ._dfdb ,_dcgf );_gbc ._dbb =append (_gbc ._dbb ,_bfac );_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,_bfac );_baa :=_adc .NewRelationships ();_cfeb .AddTarget (_a .RelationsPathFor (_caaa ),_baa .X (),_abee ,0);
if len (_gbc ._bcg )>=_bfac {_gbc ._bcg [_bfac -1]=_baa ;}else {_gbc ._bcg =append (_gbc ._bcg ,_baa );};};};case _ge .SlideLayoutType :if _aba ,_bdbd :=_ff .StringToNumbers (_caaa );_bdbd {_bga :=_db .NewSldLayout ();if !_cfeb .AddTarget (_caaa ,_bga ,_abee ,uint32 (_aba )){return nil ;
};for _bcb :=len (_gbc ._cge );_bcb < _aba ;_bcb ++{_gbc ._cge =append (_gbc ._cge ,nil );};_gbc ._cge [_aba -1]=_bga ;_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,_aba );for _faf :=len (_gbc ._bdb );_faf < _aba ;_faf ++{_gbc ._bdb =append (_gbc ._bdb ,_adc .NewRelationships ());
};_bedd :=_adc .NewRelationships ();_cfeb .AddTarget (_a .RelationsPathFor (_caaa ),_bedd .X (),_abee ,0);_gbc ._bdb [_aba -1]=_bedd ;};case _ge .ThumbnailType :for _bcaa ,_eced :=range _acf {if _eced ==nil {continue ;};if _eced .Name ==_caaa {_facg ,_bbgd :=_eced .Open ();
if _bbgd !=nil {return _dc .Errorf ("e\u0072\u0072\u006f\u0072\u0020\u0072e\u0061\u0064\u0069\u006e\u0067\u0020\u0074\u0068\u0075m\u0062\u006e\u0061i\u006c:\u0020\u0025\u0073",_bbgd );};if _gbc .Thumbnail ,_ ,_bbgd =_ee .Decode (_facg );_bbgd !=nil {return _dc .Errorf ("\u0065\u0072\u0072\u006fr\u0020\u0064\u0065\u0063\u006f\u0064\u0069\u006e\u0067\u0020t\u0068u\u006d\u0062\u006e\u0061\u0069\u006c\u003a \u0025\u0073",_bbgd );
};if _ecaa :=_facg .Close ();_ecaa !=nil {return _dc .Errorf ("e\u0072\u0072\u006f\u0072\u0020\u0063l\u006f\u0073\u0069\u006e\u0067\u0020\u0074\u0068\u0075m\u0062\u006e\u0061i\u006c:\u0020\u0025\u0073",_ecaa );};_acf [_bcaa ]=nil ;};};case _ge .ThemeType :if _eacaf ,_fdb :=_ff .StringToNumbers (_caaa );
_fdb {if len (_gbc ._gfd )< _eacaf {_dfef :=_ag .NewTheme ();if !_cfeb .AddTarget (_caaa ,_dfef ,_abee ,uint32 (_eacaf )){return nil ;};_gbc ._gfd =append (_gbc ._gfd ,_dfef );_gbc ._fbc =append (_gbc ._fbc ,_eacaf );_ecfc .TargetAttr =_ge .RelativeFilename (_gcb ,_ffbc .Typ ,_abee ,_eacaf );
_adg :=_adc .NewRelationships ();_cfeb .AddTarget (_a .RelationsPathFor (_caaa ),_adg .X (),_abee ,0);if len (_gbc ._gbfbc )>=_eacaf {_gbc ._gbfbc [_eacaf -1]=_adg ;}else {_gbc ._gbfbc =append (_gbc ._gbfbc ,_adg );};};};case _ge .ImageType :_caaa =_af .Clean (_caaa );
if _baae ,_aag :=_gbc ._gbe [_caaa ];_aag {_ecfc .TargetAttr =_baae ;return nil ;};_ggb :="";for _gdg ,_bbca :=range _acf {if _bbca ==nil {continue ;};if _bbca .Name ==_caaa {_dccc ,_baegb :=_a .ExtractToDiskTmp (_bbca ,_gbc .TmpPath );if _baegb !=nil {return _baegb ;
};_abae ,_baegb :=_adc .ImageFromStorage (_dccc );if _baegb !=nil {return _baegb ;};_ggb =_abae .Format ;if _abae .Format =="\u006a\u0070\u0065\u0067"&&_b .HasSuffix (_caaa ,"\u006a\u0070\u0067"){_ggb ="\u006a\u0070\u0067";};_gec :=_adc .MakeImageRef (_abae ,&_gbc .DocBase ,_gbc ._ddcf );
_gec .SetTarget ("\u002e\u002e\u002f"+_caaa [4:]);_gbc .Images =append (_gbc .Images ,_gec );_acf [_gdg ]=nil ;_cefc :=len (_gbc .Images );if _dcbe ,_bag :=_ff .StringToNumbers (_caaa );_bag {_cefc =_dcbe ;};_cfeb .RecordIndex (_caaa ,_cefc );break ;};
};_afgf :=_cfeb .IndexFor (_caaa );_ecfc .TargetAttr =_ge .RelativeImageFilename (_gcb ,_ffbc .Typ ,_abee ,_afgf ,_ggb );_gbc ._gbe [_caaa ]=_ecfc .TargetAttr ;default:_dd .Log .Debug ("\u0075\u006e\u0073\u0075\u0070p\u006f\u0072\u0074\u0065\u0064\u0020\u0072\u0065\u006c\u0061\u0074\u0069\u006fn\u0073\u0068\u0069\u0070\u0020\u0074\u0079\u0070\u0065\u003a\u0020\u0025\u0073\u0020\u0074\u0067\u0074\u003a\u0020\u0025\u0073",_abee ,_caaa );
};return nil ;};

// ExtractText returns text from a presentation as a PresentationText object.
func (_ddb *Presentation )ExtractText ()*PresentationText {_cb :=[]*SlideText {};for _ ,_bcf :=range _ddb .Slides (){_eb :=_bcf .ExtractText ();if _eb !=nil {_cb =append (_cb ,_eb );};};return &PresentationText {Slides :_cb };};

// SetHeight sets height of slide screen size with given value in EMU units.
func (_eec *SlideScreenSize )SetHeight (val int32 ){_eec [1]=val };

// Height returns slide screen size height in EMU units.
func (_dagd *SlideScreenSize )Height ()int32 {return _dagd [1]};

// NotesTextViewPr returns the NotesTextViewPr property.
func (_fdagf ViewProperties )NotesTextViewPr ()*_db .CT_NotesTextViewProperties {return _fdagf ._dgeb .NotesTextViewPr ;};

// NewViewProperties constructs a new ViewProperties.
func NewViewProperties ()ViewProperties {return ViewProperties {_dgeb :_db .NewViewPr ()}};

// Presentation is the a presentation base document.
type Presentation struct{_adc .DocBase ;_agc *_db .Presentation ;_ddcf _adc .Relationships ;_ggcc []*_db .Sld ;_bcd []_adc .Relationships ;_ege []int ;_dfdb []*_db .SldMaster ;_bcg []_adc .Relationships ;_dbb []int ;_cge []*_db .SldLayout ;_bdb []_adc .Relationships ;
_gfd []*_ag .Theme ;_gbfbc []_adc .Relationships ;_fbc []int ;_eda _adc .TableStyles ;_dcd PresentationProperties ;_cdad ViewProperties ;_gfg []*_ag .CT_Hyperlink ;_efa []*chart ;_beb []*_db .HandoutMaster ;_cce []*_db .NotesMaster ;_ffd []int ;_cdeg []*_ge .XSDAny ;
_aafa []int ;_gbe map[string ]string ;_bddf string ;};

// GetPlaceholder returns a placeholder given its type.  If there are multiplace
// placeholders of the same type, this method returns the first one.  You must use the
// PlaceHolders() method to access the others.
func (_gdc Slide )GetPlaceholder (t _db .ST_PlaceholderType )(PlaceHolder ,error ){for _ ,_dabg :=range _gdc ._fea .CSld .SpTree .GroupShapeChoice {if _dabg .Sp !=nil &&_dabg .Sp .NvSpPr !=nil &&_dabg .Sp .NvSpPr .NvPr !=nil &&_dabg .Sp .NvSpPr .NvPr .Ph !=nil {if _dabg .Sp .NvSpPr .NvPr .Ph .TypeAttr ==t {return PlaceHolder {_dabg .Sp ,_gdc ._fea },nil ;
};};};return PlaceHolder {},_ab .New ("\u0075\u006e\u0061\u0062\u006c\u0065\u0020\u0074\u006f\u0020\u0066i\u006e\u0064\u0020\u0070\u006c\u0061\u0063\u0065\u0068\u006fl\u0064\u0065\u0072");};

// GetTextBoxes returns a list of all text boxes from a slide.
func (_dcgg Slide )GetTextBoxes ()[]*TextBox {_gba :=[]*TextBox {};_fbdaf :=_dcgg ._fea .CSld .SpTree .GroupShapeChoice ;for _ ,_bedb :=range _fbdaf {if _bedb .Sp !=nil &&_bedb .Sp .NvSpPr .CNvSpPr .TxBoxAttr !=nil &&*_bedb .Sp .NvSpPr .CNvSpPr .TxBoxAttr {_gba =append (_gba ,&TextBox {_bedb .Sp });
};};return _gba ;};

// AddTable adds an empty table to a slide.
func (_cffb Slide )AddTable ()*_adc .Table {_eag :=_db .NewCT_GroupShapeChoice ();_cffb ._fea .CSld .SpTree .GroupShapeChoice =append (_cffb ._fea .CSld .SpTree .GroupShapeChoice ,_eag );_deef :=_db .NewCT_GraphicalObjectFrame ();_eag .GraphicFrame =_deef ;
_deef .Xfrm .Off =_ag .NewCT_Point2D ();_dbba :=int64 (1);_deef .Xfrm .Off .XAttr =_ag .ST_Coordinate {ST_CoordinateUnqualified :&_dbba };_deef .Xfrm .Off .YAttr =_ag .ST_Coordinate {ST_CoordinateUnqualified :&_dbba };_ffcb :=_deef .Graphic .CT_GraphicalObject .GraphicData ;
_ffcb .UriAttr ="\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002eo\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073.\u006f\u0072\u0067\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u006dl/\u0032\u0030\u0030\u0036\u002f\u0074\u0061\u0062\u006c\u0065";
_caadf :=_adc .NewTableWithXfrm (_deef .Xfrm );_ffcb .Any =append (_ffcb .Any ,_caadf .X ());return _caadf ;};

// Sid returns the sid of slide
func (_accg Slide )Sid ()*_db .CT_SlideIdListEntry {return _accg ._cddgg };func _ade (_bcfg *Presentation ,_eee []*_db .CT_GroupShapeChoice ,_cd []rectangle ,_fgc []*TextItem )[]*TextItem {for _ ,_ae :=range _eee {_bb :=append ([]rectangle {},_cd ...);
if _ae .Sp !=nil {_fgc =append (_fgc ,_dca (_bcfg ,_ae .Sp ,nil ,nil ,_ae .Sp .SpPr .Xfrm ,0,_cd ,_ae .Sp .TxBody .P )...);};if _ae .GraphicFrame !=nil &&_ae .GraphicFrame .Graphic !=nil &&_ae .GraphicFrame .Graphic .GraphicData !=nil {_bbg :=_ae .GraphicFrame .Xfrm ;
for _ ,_cdc :=range _ae .GraphicFrame .Graphic .GraphicData .Any {if _gac ,_cdcg :=_cdc .(*_ag .Tbl );_cdcg {_cbg :=&_gac .CT_Table ;_edb :=0;for _fcd ,_gf :=range _gac .Tr {for _cba ,_fgd :=range _gf .Tc {_de :=&TableInfo {Table :_cbg ,Row :_gf ,Cell :_fgd ,RowIndex :_fcd ,ColIndex :_cba };
_fgc =append (_fgc ,_dca (_bcfg ,nil ,_ae .GraphicFrame ,_de ,_bbg ,_edb ,_cd ,_fgd .TxBody .P )...);_edb ++;};};};};};if _ae .GrpSp !=nil {if _ae .GrpSp .GrpSpPr !=nil {_abf :=_ae .GrpSp .GrpSpPr .Xfrm ;var _bdd ,_ba int64 ;if _abf .Off !=nil {_age ,_bf :=_abf .Off .XAttr .ST_CoordinateUnqualified ,_abf .Off .YAttr .ST_CoordinateUnqualified ;
if _age !=nil &&_bf !=nil {if _ggc :=_abf .Ext ;_ggc !=nil {_bdd ,_ba =_ggc .CxAttr ,_ggc .CyAttr ;};_bb =append (_bb ,rectangle {_c :*_age ,_cc :*_bf ,_efbf :*_age +_bdd ,_cca :*_bf +_ba });};};};_fgc =_ade (_bcfg ,_ae .GrpSp .GroupShapeChoice ,_bb ,_fgc );
};};return _fgc ;};var (SlideScreenSize16x9 =SlideScreenSize {12192000,6858000};SlideScreenSize4x3 =SlideScreenSize {9144000,6858000};SlideScreenSizeA4 =SlideScreenSize {9906000,6858000};);

// AddTextBox adds an empty textbox to a slide.
func (_bfeg Slide )AddTextBox ()TextBox {_gfgc :=_db .NewCT_GroupShapeChoice ();_bfeg ._fea .CSld .SpTree .GroupShapeChoice =append (_bfeg ._fea .CSld .SpTree .GroupShapeChoice ,_gfgc );_fbda :=_db .NewCT_Shape ();_gfgc .Sp =_fbda ;_fbda .SpPr =_ag .NewCT_ShapeProperties ();
_fbda .SpPr .Xfrm =_ag .NewCT_Transform2D ();_fbda .SpPr .GeometryChoice .PrstGeom =_ag .NewCT_PresetGeometry2D ();_fbda .SpPr .GeometryChoice .PrstGeom .PrstAttr =_ag .ST_ShapeTypeRect ;_fbda .NvSpPr =_db .NewCT_ShapeNonVisual ();_fbda .NvSpPr .CNvSpPr =_ag .NewCT_NonVisualDrawingShapeProps ();
_abgg :=true ;_fbda .NvSpPr .CNvSpPr .TxBoxAttr =&_abgg ;_fbda .TxBody =_ag .NewCT_TextBody ();_fbda .TxBody .BodyPr =_ag .NewCT_TextBodyProperties ();_fbda .TxBody .BodyPr .WrapAttr =_ag .ST_TextWrappingTypeSquare ;_fbda .TxBody .BodyPr .TextAutofitChoice .SpAutoFit =_ag .NewCT_TextShapeAutofit ();
_bgcd :=TextBox {_fbda };_bgcd .Properties ().SetWidth (3*_ea .Inch );_bgcd .Properties ().SetHeight (1*_ea .Inch );_bgcd .Properties ().SetPosition (0,0);return _bgcd ;};

// SlideLayout is a layout from which slides can be created.
type SlideLayout struct{_fcea *_db .SldLayout };

// Tables returns all of the tables within a given slide.
func (_ebbe Slide )Tables ()[]*_adc .Table {_gbdb :=[]*_adc .Table {};_abg :=_ebbe .X ().CSld ;if _gfgf :=_abg .SpTree ;_gfgf !=nil {for _ ,_fcdg :=range _gfgf .GroupShapeChoice {if _fcdg .GraphicFrame !=nil &&_fcdg .GraphicFrame .Graphic !=nil &&_fcdg .GraphicFrame .Graphic .GraphicData !=nil {for _ ,_gefc :=range _fcdg .GraphicFrame .Graphic .GraphicData .Any {if _fedf ,_gcbe :=_gefc .(*_ag .Tbl );
_gcbe {_gcba :=_adc .NewTableFromTbl (_fedf ,_fcdg .GraphicFrame .Xfrm );_gbdb =append (_gbdb ,_gcba );};};};};};return _gbdb ;};

// X returns the inner wrapped XML type.
func (_eedea Slide )X ()*_db .Sld {return _eedea ._fea };type chart struct{_ga *_g .ChartSpace ;_fc string ;_aab string ;};

// ClrMru returns the ClrMru property.
func (_ecb PresentationProperties )ClrMru ()*_ag .CT_ColorMRU {return _ecb ._gbdc .ClrMru };

// X returns the inner wrapped XML type.
func (_ggd PresentationProperties )X ()*_db .PresentationPr {return _ggd ._gbdc };

// GetSlideLayout returns a slide layout related to the slide.
func (_abag *Slide )GetSlideLayout ()*_db .SldLayout {_adaa :=_abag .getSlideRels ();for _ ,_dfg :=range _adaa .Relationships (){if _dfg .Type ()==_ge .SlideLayoutType {if _dbcb ,_edae :=_ff .StringToNumbers (_dfg .Target ());_edae {return _abag ._agab ._cge [_dbcb -1];
};return nil ;};};return nil ;};

// TextBox is a text box within a slide.
type TextBox struct{_gff *_db .CT_Shape };

// PrnPr returns the PrnPr property.
func (_bcfa PresentationProperties )PrnPr ()*_db .CT_PrintProperties {return _bcfa ._gbdc .PrnPr };

// SetSize sets the slide size, take argument of SlideScreenSize.
func (_abd *SlideSize )SetSize (sz SlideScreenSize ){_abd ._bfce .CxAttr =sz [0];_abd ._bfce .CyAttr =sz [1];};

// AddImage adds an image textbox to a slide.
func (_bdbbb Slide )AddImage (img _adc .ImageRef )Image {_gfb :=_db .NewCT_GroupShapeChoice ();_bdbbb ._fea .CSld .SpTree .GroupShapeChoice =append (_bdbbb ._fea .CSld .SpTree .GroupShapeChoice ,_gfb );_fcbf :=_db .NewCT_Picture ();_gfb .Pic =_fcbf ;_fcbf .NvPicPr .CNvPicPr =_ag .NewCT_NonVisualPictureProperties ();
_fcbf .NvPicPr .CNvPicPr .PicLocks =_ag .NewCT_PictureLocking ();_fcbf .NvPicPr .CNvPicPr .PicLocks .NoChangeAspectAttr =_ge .Bool (true );_fcbf .BlipFill =_ag .NewCT_BlipFillProperties ();_fcbf .BlipFill .Blip =_ag .NewCT_Blip ();_fbag :=_bdbbb .AddImageToRels (img );
_fcbf .BlipFill .Blip .EmbedAttr =_ge .String (_fbag );_fcbf .BlipFill .FillModePropertiesChoice .Stretch =_ag .NewCT_StretchInfoProperties ();_fcbf .BlipFill .FillModePropertiesChoice .Stretch .FillRect =_ag .NewCT_RelativeRect ();_fcbf .SpPr =_ag .NewCT_ShapeProperties ();
_fcbf .SpPr .GeometryChoice .PrstGeom =_ag .NewCT_PresetGeometry2D ();_fcbf .SpPr .GeometryChoice .PrstGeom .PrstAttr =_ag .ST_ShapeTypeRect ;_cfff :=Image {_fcbf };_dfcf :=img .Size ();_cfff .Properties ().SetWidth (_ea .Distance (_dfcf .X )*_ea .Pixel72 );
_cfff .Properties ().SetHeight (_ea .Distance (_dfcf .Y )*_ea .Pixel72 );_cfff .Properties ().SetPosition (0,0);return _cfff ;};

// SetTextAnchor controls the text anchoring
func (_fead TextBox )SetTextAnchor (a _ag .ST_TextAnchoringType ){_fead ._gff .TxBody .BodyPr =_ag .NewCT_TextBodyProperties ();_fead ._gff .TxBody .BodyPr .AnchorAttr =a ;};

// Read reads a document from an io.Reader.
func Read (r _fd .ReaderAt ,size int64 )(*Presentation ,error ){const _agb ="\u0070\u0072\u0065\u0073\u0065\u006e\u0074\u0061\u0074\u0069\u006f\u006e:\u0052\u0065\u0061\u0064";if !_ef .GetLicenseKey ().IsLicensed ()&&!_gcf {_dc .Println ("\u0055\u006e\u006ci\u0063\u0065\u006e\u0073e\u0064\u0020\u0076\u0065\u0072\u0073\u0069o\u006e\u0020\u006f\u0066\u0020\u0055\u006e\u0069\u004f\u0066\u0066\u0069\u0063\u0065");
_dc .Println ("\u002d\u0020\u0047e\u0074\u0020\u0061\u0020\u0074\u0072\u0069\u0061\u006c\u0020\u006c\u0069\u0063\u0065\u006e\u0073\u0065\u0020\u006f\u006e\u0020\u0068\u0074\u0074\u0070\u0073\u003a\u002f\u002fu\u006e\u0069\u0064\u006f\u0063\u002e\u0069\u006f");
return nil ,_ab .New ("\u0075\u006e\u0069\u006f\u0066\u0066\u0069\u0063\u0065\u0020\u006ci\u0063\u0065\u006e\u0073\u0065\u0020\u0072\u0065\u0071\u0075i\u0072\u0065\u0064");};_bbdg :="\u0075n\u006b\u006e\u006f\u0077\u006e";if _gaag ,_aedd :=r .(*_eg .File );
_aedd {_bbdg =_gaag .Name ();};_ddcff :=_dg ();_aecg ,_fed :=_ef .GenRefId ("\u0070\u0072");if _fed !=nil {_dd .Log .Error ("\u0045R\u0052\u004f\u0052\u003a\u0020\u0025v",_fed );return nil ,_fed ;};_ddcff ._bddf =_aecg ;if _eede :=_ef .Track (_ddcff ._bddf ,_agb ,_bbdg );
_eede !=nil {_dd .Log .Error ("\u0045R\u0052\u004f\u0052\u003a\u0020\u0025v",_eede );return nil ,_eede ;};_bcfgf ,_fed :=_ad .TempDir ("\u0075\u006e\u0069\u006f\u0066\u0066\u0069\u0063\u0065-\u0070\u0070\u0074\u0078");if _fed !=nil {return nil ,_fed ;};
_ddcff .TmpPath =_bcfgf ;_fbaae ,_fed :=_gg .NewReader (r ,size );if _fed !=nil {return nil ,_dc .Errorf ("\u0070a\u0072s\u0069\u006e\u0067\u0020\u007a\u0069\u0070\u003a\u0020\u0025\u0073",_fed );};_ggdd :=[]*_gg .File {};_ggdd =append (_ggdd ,_fbaae .File ...);
_bgb :=false ;for _ ,_aaa :=range _ggdd {if _aaa .FileHeader .Name =="\u0064\u006f\u0063\u0050ro\u0070\u0073\u002f\u0063\u0075\u0073\u0074\u006f\u006d\u002e\u0078\u006d\u006c"{_bgb =true ;break ;};};if _bgb {_ddcff .CreateCustomProperties ();};_gcd :=_a .DecodeMap {};
_gcd .SetOnNewRelationshipFunc (_ddcff .onNewRelationship );_gcd .AddTarget (_ge .ContentTypesFilename ,_ddcff .ContentTypes .X (),"",0);_gcd .AddTarget (_ge .BaseRelsFilename ,_ddcff .Rels .X (),"",0);if _efgcc :=_gcd .Decode (_ggdd );_efgcc !=nil {return nil ,_efgcc ;
};for _ ,_bdfb :=range _ggdd {if _bdfb ==nil {continue ;};if _dbbc :=_ddcff .AddExtraFileFromZip (_bdfb );_dbbc !=nil {return nil ,_dbbc ;};};if _bgb {_fgae :=false ;for _ ,_dagc :=range _ddcff .Rels .X ().Relationship {if _dagc .TargetAttr =="\u0064\u006f\u0063\u0050ro\u0070\u0073\u002f\u0063\u0075\u0073\u0074\u006f\u006d\u002e\u0078\u006d\u006c"{_fgae =true ;
break ;};};if !_fgae {_ddcff .AddCustomRelationships ();};};return _ddcff ,nil ;};

// AddSlide adds a new slide to the presentation.
func (_ddd *Presentation )AddSlide ()Slide {_ffg :=_db .NewCT_SlideIdListEntry ();_ffg .IdAttr =_ddd .nextSlideID ();_ddd ._agc .SldIdLst .SldId =append (_ddd ._agc .SldIdLst .SldId ,_ffg );_gabf :=_db .NewSld ();_gabf .CSld .SpTree .NvGrpSpPr .CNvPr .IdAttr =1;
_gabf .CSld .SpTree .GrpSpPr .Xfrm =_ag .NewCT_GroupTransform2D ();_gabf .CSld .SpTree .GrpSpPr .Xfrm .Off =_ag .NewCT_Point2D ();_gabf .CSld .SpTree .GrpSpPr .Xfrm .Off .XAttr .ST_CoordinateUnqualified =_ge .Int64 (0);_gabf .CSld .SpTree .GrpSpPr .Xfrm .Off .YAttr .ST_CoordinateUnqualified =_ge .Int64 (0);
_gabf .CSld .SpTree .GrpSpPr .Xfrm .Ext =_ag .NewCT_PositiveSize2D ();_gabf .CSld .SpTree .GrpSpPr .Xfrm .Ext .CxAttr =int64 (0*_ea .Point );_gabf .CSld .SpTree .GrpSpPr .Xfrm .Ext .CyAttr =int64 (0*_ea .Point );_gabf .CSld .SpTree .GrpSpPr .Xfrm .ChOff =_gabf .CSld .SpTree .GrpSpPr .Xfrm .Off ;
_gabf .CSld .SpTree .GrpSpPr .Xfrm .ChExt =_gabf .CSld .SpTree .GrpSpPr .Xfrm .Ext ;_ddd ._ggcc =append (_ddd ._ggcc ,_gabf );_ddd ._ege =append (_ddd ._ege ,len (_ddd ._ggcc ));_dea :=_ddd ._ddcf .AddAutoRelationship (_ge .DocTypePresentation ,_ge .OfficeDocumentType ,len (_ddd ._ggcc ),_ge .SlideType );
_ffg .RIdAttr =_dea .ID ();_bdbb :=_ge .AbsoluteFilename (_ge .DocTypePresentation ,_ge .SlideType ,len (_ddd ._ggcc ));_ddd .ContentTypes .AddOverride (_bdbb ,_ge .SlideContentType );_gebc :=_adc .NewRelationships ();_ddd ._bcd =append (_ddd ._bcd ,_gebc );
_gebc .AddAutoRelationship (_ge .DocTypePresentation ,_ge .SlideType ,len (_ddd ._cge ),_ge .SlideLayoutType );return Slide {_ffg ,_gabf ,_ddd ,nil };};

// SlideScreenSize represents the slide screen size as a 2 element array
// representing the width and height in EMU units.
type SlideScreenSize [2]int32 ;

// GetImageByRelID returns an ImageRef with the associated relation ID in the
// slide.
func (_fff *Slide )GetImageByRelID (relID string )(_adc .ImageRef ,bool ){_bfde :=_fff .getSlideRels ();if (_bfde ==_adc .Relationships {}){return _adc .ImageRef {},false ;};_ecbe :=_bfde .GetTargetByRelId (relID );for _ ,_gcea :=range _fff ._agab .Images {if _gcea .Target ()==_ecbe {return _gcea ,true ;
};};return _adc .ImageRef {},false ;};

// OutlineViewPr returns the OutlineViewPr property.
func (_defc ViewProperties )OutlineViewPr ()*_db .CT_OutlineViewProperties {return _defc ._dgeb .OutlineViewPr ;};

// Clear clears the placeholder contents and adds a single empty paragraph.  The
// empty paragrah is required by PowerPoint or it will report the file as being
// invalid.
func (_fcf PlaceHolder )Clear (){_fcf .ClearAll ();_cbad :=_ag .NewCT_TextParagraph ();_fcf ._abfg .TxBody .P =[]*_ag .CT_TextParagraph {_cbad };_cbad .EndParaRPr =_ag .NewCT_TextCharacterProperties ();_cbad .EndParaRPr .LangAttr =_ge .String ("\u0065\u006e\u002dU\u0053");
};

// Name returns the name of the slide layout.
func (_aabbb SlideLayout )Name ()string {if _aabbb ._fcea .CSld !=nil &&_aabbb ._fcea .CSld .NameAttr !=nil {return *_aabbb ._fcea .CSld .NameAttr ;};return "";};func _dg ()*Presentation {_fgb :=&Presentation {_agc :_db .NewPresentation ()};_fgb ._agc .SldIdLst =_db .NewCT_SlideIdList ();
_fgb ._agc .ConformanceAttr =_d .ST_ConformanceClassTransitional ;_fgb .AppProperties =_adc .NewAppProperties ();_fgb .CoreProperties =_adc .NewCoreProperties ();_fgb ._eda =_adc .NewTableStyles ();_fgb .ContentTypes =_adc .NewContentTypes ();_fgb .Rels =_adc .NewRelationships ();
_fgb ._ddcf =_adc .NewRelationships ();_fgb ._dcd =NewPresentationProperties ();_fgb ._cdad =NewViewProperties ();_fgb ._gbe =map[string ]string {};return _fgb ;};

// X returns the inner wrapped XML type.
func (_aecge SlideMaster )X ()*_db .SldMaster {return _aecge ._dec };

// Image is an image within a slide.
type Image struct{_ffc *_db .CT_Picture };

// SlideMaster is the slide master for a presentation.
type SlideMaster struct{_dfb *Presentation ;_dcec _adc .Relationships ;_dec *_db .SldMaster ;};

// Save writes the presentation out to a writer in the Zip package format
func (_efe *Presentation )Save (w _fd .Writer )error {return _efe .save (w ,false )};

// GetChartSpaceByRelId returns a *crt.ChartSpace with the associated relation ID in the
// slide.
func (_gdd *Slide )GetChartSpaceByRelId (relId string )*_g .ChartSpace {_ebe :=_gdd .getSlideRels ();if (_ebe ==_adc .Relationships {}){return nil ;};_gbgb :=_ebe .GetTargetByRelId (relId );for _ ,_efad :=range _gdd ._agab ._efa {if _gbgb ==_efad .Target (){return _efad ._ga ;
};};return nil ;};

// Size returns slide size value as SlideScreenSize.
func (_deff *SlideSize )Size ()SlideScreenSize {return SlideScreenSize {_deff ._bfce .CxAttr ,_deff ._bfce .CyAttr };};

// ClearAll completely clears a placeholder. To be useable, at least one
// paragraph must be added after ClearAll via AddParagraph.
func (_eaca PlaceHolder )ClearAll (){_eaca ._abfg .SpPr =_ag .NewCT_ShapeProperties ();_eaca ._abfg .TxBody =_ag .NewCT_TextBody ();_eaca ._abfg .TxBody .LstStyle =_ag .NewCT_TextListStyle ();};func (_gga sort2d )Len ()int {return len (_gga )};

// AddParagraph adds a new paragraph to a placeholder.
func (_dce PlaceHolder )AddParagraph ()_be .Paragraph {_cfe :=_be .MakeParagraph (_ag .NewCT_TextParagraph ());_dce ._abfg .TxBody .P =append (_dce ._abfg .TxBody .P ,_cfe .X ());return _cfe ;};

// Properties returns the properties of the TextBox.
func (_gaad TextBox )Properties ()_be .ShapeProperties {if _gaad ._gff .SpPr ==nil {_gaad ._gff .SpPr =_ag .NewCT_ShapeProperties ();};return _be .MakeShapeProperties (_gaad ._gff .SpPr );};func (_efb *chart )X ()*_g .ChartSpace {return _efb ._ga };func (_gea sort2d )Swap (i ,j int ){_gea [i ],_gea [j ]=_gea [j ],_gea [i ]};


// ExtLst returns the ExtLst property.
func (_eebe PresentationProperties )ExtLst ()*_db .CT_ExtensionList {return _eebe ._gbdc .ExtLst };

// AddParagraph adds a paragraph to the text box
func (_fffa TextBox )AddParagraph ()_be .Paragraph {_efdc :=_ag .NewCT_TextParagraph ();_fffa ._gff .TxBody .P =append (_fffa ._gff .TxBody .P ,_efdc );return _be .MakeParagraph (_efdc );};func (_dgd *Presentation )nextSlideID ()uint32 {_ebb :=uint32 (256);
for _ ,_dff :=range _dgd ._agc .SldIdLst .SldId {if _dff .IdAttr >=_ebb {_ebb =_dff .IdAttr +1;};};return _ebb ;};

// AddImage adds an image to the document package, returning a reference that
// can be used to add the image to a run and place it in the document contents.
func (_geg *Presentation )AddImage (i _adc .Image )(_adc .ImageRef ,error ){_fbaa :=_adc .MakeImageRef (i ,&_geg .DocBase ,_geg ._ddcf );if i .Data ==nil &&i .Path ==""{return _fbaa ,_ab .New ("\u0069\u006d\u0061\u0067\u0065\u0020\u006d\u0075\u0073\u0074 \u0068\u0061\u0076\u0065\u0020\u0064\u0061t\u0061\u0020\u006f\u0072\u0020\u0061\u0020\u0070\u0061\u0074\u0068");
};if i .Format ==""{return _fbaa ,_ab .New ("\u0069\u006d\u0061\u0067\u0065\u0020\u006d\u0075\u0073\u0074 \u0068\u0061\u0076\u0065\u0020\u0061\u0020v\u0061\u006c\u0069\u0064\u0020\u0066\u006f\u0072\u006d\u0061\u0074");};if i .Size .X ==0||i .Size .Y ==0{return _fbaa ,_ab .New ("\u0069\u006d\u0061\u0067e\u0020\u006d\u0075\u0073\u0074\u0020\u0068\u0061\u0076\u0065 \u0061 \u0076\u0061\u006c\u0069\u0064\u0020\u0073i\u007a\u0065");
};if i .Path !=""{_gegd :=_ad .Add (i .Path );if _gegd !=nil {return _fbaa ,_gegd ;};};_geg .Images =append (_geg .Images ,_fbaa );_geg .ContentTypes .EnsureDefault ("\u0070\u006e\u0067","\u0069m\u0061\u0067\u0065\u002f\u0070\u006eg");_geg .ContentTypes .EnsureDefault ("\u006a\u0070\u0065\u0067","\u0069\u006d\u0061\u0067\u0065\u002f\u006a\u0070\u0065\u0067");
_geg .ContentTypes .EnsureDefault ("\u006a\u0070\u0067","\u0069\u006d\u0061\u0067\u0065\u002f\u006a\u0070\u0065\u0067");_geg .ContentTypes .EnsureDefault ("\u0077\u006d\u0066","i\u006d\u0061\u0067\u0065\u002f\u0078\u002d\u0077\u006d\u0066");_geg .ContentTypes .EnsureDefault (i .Format ,"\u0069\u006d\u0061\u0067\u0065\u002f"+i .Format );
return _fbaa ,nil ;};

// GridSpacing returns the GridSpacing property.
func (_fef ViewProperties )GridSpacing ()*_ag .CT_PositiveSize2D {return _fef ._dgeb .GridSpacing };

// SorterViewPr returns the SorterViewPr property.
func (_abc ViewProperties )SorterViewPr ()*_db .CT_SlideSorterViewProperties {return _abc ._dgeb .SorterViewPr ;};func (_ddea *Slide )ensureClrMap (){if len (_ddea ._agab ._dfdb )==0||len (_ddea ._agab ._gfd )==0{return ;};_aedc :=_ddea ._agab ._dfdb [0];
_gagc :=_aedc .ClrMap ;if _fbaad :=_ddea ._fea .ClrMapOvr ;_fbaad !=nil {if _fae :=_fbaad .ColorMappingOverrideChoice ;_fae !=nil {if _fae .MasterClrMapping ==nil {if _geag :=_fae .OverrideClrMapping ;_geag !=nil {if _geag .Bg1Attr !=_ag .ST_ColorSchemeIndexUnset {_gagc .Bg1Attr =_geag .Bg1Attr ;
};if _geag .Tx1Attr !=_ag .ST_ColorSchemeIndexUnset {_gagc .Tx1Attr =_geag .Tx1Attr ;};if _geag .Bg2Attr !=_ag .ST_ColorSchemeIndexUnset {_gagc .Bg2Attr =_geag .Bg2Attr ;};if _geag .Tx2Attr !=_ag .ST_ColorSchemeIndexUnset {_gagc .Tx2Attr =_geag .Tx2Attr ;
};if _geag .Accent1Attr !=_ag .ST_ColorSchemeIndexUnset {_gagc .Accent1Attr =_geag .Accent1Attr ;};if _geag .Accent2Attr !=_ag .ST_ColorSchemeIndexUnset {_gagc .Accent2Attr =_geag .Accent2Attr ;};if _geag .Accent3Attr !=_ag .ST_ColorSchemeIndexUnset {_gagc .Accent3Attr =_geag .Accent3Attr ;
};if _geag .Accent4Attr !=_ag .ST_ColorSchemeIndexUnset {_gagc .Accent4Attr =_geag .Accent4Attr ;};if _geag .Accent5Attr !=_ag .ST_ColorSchemeIndexUnset {_gagc .Accent5Attr =_geag .Accent5Attr ;};if _geag .Accent6Attr !=_ag .ST_ColorSchemeIndexUnset {_gagc .Accent6Attr =_geag .Accent6Attr ;
};if _geag .HlinkAttr !=_ag .ST_ColorSchemeIndexUnset {_gagc .HlinkAttr =_geag .HlinkAttr ;};if _geag .FolHlinkAttr !=_ag .ST_ColorSchemeIndexUnset {_gagc .FolHlinkAttr =_geag .FolHlinkAttr ;};};};};};_ddea ._dgg =_gagc ;};

// ShowCommentsAttr returns the WebPr property.
func (_gbdg ViewProperties )ShowCommentsAttr ()*bool {return _gbdg ._dgeb .ShowCommentsAttr };func (_fgcca *Presentation )Validate ()error {if _bbd :=_fgcca ._agc .Validate ();_bbd !=nil {return _bbd ;};for _baeg ,_agad :=range _fgcca .Slides (){if _dge :=_agad .ValidateWithPath (_dc .Sprintf ("\u0053l\u0069\u0064\u0065\u005b\u0025\u0064]",_baeg ));
_dge !=nil {return _dge ;};};for _bgggf ,_ccg :=range _fgcca ._dfdb {if _gebce :=_ccg .ValidateWithPath (_dc .Sprintf ("\u0053l\u0069d\u0065\u004d\u0061\u0073\u0074\u0065\u0072\u005b\u0025\u0064\u005d",_bgggf ));_gebce !=nil {return _gebce ;};};for _cbgf ,_abfa :=range _fgcca ._cge {if _bfed :=_abfa .ValidateWithPath (_dc .Sprintf ("\u0053l\u0069d\u0065\u004c\u0061\u0079\u006f\u0075\u0074\u005b\u0025\u0064\u005d",_cbgf ));
_bfed !=nil {return _bfed ;};};return nil ;};

// Remove removes a placeholder from a presentation.
func (_eabd PlaceHolder )Remove ()error {for _fcfd ,_egd :=range _eabd ._gdb .CSld .SpTree .GroupShapeChoice {if _egd .Sp !=nil &&_egd .Sp ==_eabd ._abfg {copy (_eabd ._gdb .CSld .SpTree .GroupShapeChoice [_fcfd :],_eabd ._gdb .CSld .SpTree .GroupShapeChoice [_fcfd +1:]);
_eabd ._gdb .CSld .SpTree .GroupShapeChoice =_eabd ._gdb .CSld .SpTree .GroupShapeChoice [0:len (_eabd ._gdb .CSld .SpTree .GroupShapeChoice )-1];return nil ;};};return _ab .New ("\u0070\u006c\u0061\u0063\u0065\u0068\u006f\u006c\u0064\u0065r\u0020\u006e\u006f\u0074\u0020\u0066\u006fu\u006e\u0064\u0020\u0069\u006e\u0020\u0073\u006c\u0069\u0064\u0065");
};

// AddDefaultSlideWithLayout tries to replicate what PowerPoint does when
// inserting a slide with a new style by clearing placeholder content and removing
// some placeholders.  Use AddSlideWithLayout if you need more control.
func (_eff *Presentation )AddDefaultSlideWithLayout (l SlideLayout )(Slide ,error ){_bdgc ,_ccae :=_eff .AddSlideWithLayout (l );for _ ,_bggf :=range _bdgc .PlaceHolders (){_bggf .Clear ();switch _bggf .Type (){case _db .ST_PlaceholderTypeFtr ,_db .ST_PlaceholderTypeDt ,_db .ST_PlaceholderTypeSldNum :if _eae :=_bggf .Remove ();
_eae !=nil {return Slide {},_eae ;};};};return _bdgc ,_ccae ;};

// GetImageByTarget returns an ImageRef with the given target in the
// document.
func (_bedf *Presentation )GetImageByTarget (target string )(_adc .ImageRef ,bool ){for _ ,_fbdd :=range _bedf .Images {if _fbdd .Target ()==target {return _fbdd ,true ;};};return _adc .ImageRef {},false ;};

// SetWidth sets width of slide screen size with given value in EMU units.
func (_fbdg *SlideScreenSize )SetWidth (val int32 ){_fbdg [0]=val };

// SetOffsetX sets horizontal offset of text box in distance units (see measurement package).
func (_dad TextBox )SetOffsetX (offX float64 ){_ccf :=_dad .getOff ();_cebe :=_ea .ToEMU (offX );_ccf .XAttr =_ag .ST_Coordinate {ST_CoordinateUnqualified :&_cebe };};func (_fbge TextBox )getOff ()*_ag .CT_Point2D {if _fbge ._gff .SpPr ==nil {_fbge ._gff .SpPr =_ag .NewCT_ShapeProperties ();
};if _fbge ._gff .SpPr .Xfrm ==nil {_fbge ._gff .SpPr .Xfrm =_ag .NewCT_Transform2D ();};if _fbge ._gff .SpPr .Xfrm .Off ==nil {_fbge ._gff .SpPr .Xfrm .Off =_ag .NewCT_Point2D ();};return _fbge ._gff .SpPr .Xfrm .Off ;};

// SlideMasters returns the slide masters defined in the presentation.
func (_fcge *Presentation )SlideMasters ()[]SlideMaster {_abb :=[]SlideMaster {};for _aff ,_bdbe :=range _fcge ._dfdb {if _aff < len (_fcge ._bcg ){_abb =append (_abb ,SlideMaster {_fcge ,_fcge ._bcg [_aff ],_bdbe });};};return _abb ;};

// ValidateWithPath validates the slide passing path informaton for a better
// error message.
func (_baea Slide )ValidateWithPath (path string )error {if _gadd :=_baea ._fea .ValidateWithPath (path );_gadd !=nil {return _gadd ;};for _ ,_gcde :=range _baea ._fea .CSld .SpTree .GroupShapeChoice {if _gcde .Sp !=nil &&_gcde .Sp .TxBody !=nil {if len (_gcde .Sp .TxBody .P )==0{return _ab .New (path +"\u0020\u003a \u0073\u006c\u0069\u0064\u0065 \u0073\u0068\u0061\u0070\u0065 \u0077\u0069\u0074\u0068\u0020\u0061\u0020\u0074\u0078\u0062\u006f\u0064\u0079\u0020\u006d\u0075\u0073\u0074\u0020\u0063\u006f\u006e\u0074\u0061\u0069\u006e\u0020\u0070\u0061\u0072\u0061\u0067\u0072\u0061\u0070\u0068\u0073");
};};};return nil ;};

// NotesViewPr returns the NotesViewPr property.
func (_bgdaf ViewProperties )NotesViewPr ()*_db .CT_NotesViewProperties {return _bgdaf ._dgeb .NotesViewPr ;};func (_ed *chart )RelId ()string {return _ed ._fc };

// SaveToFile writes the Presentation out to a file.
func (_ccdbb *Presentation )SaveToFile (path string )error {return _ccdbb .saveToFile (path ,false )};

// AddImageToRels adds an image relationship to a slide without putting image on the slide.
func (_ddg Slide )AddImageToRels (img _adc .ImageRef )string {_dcag :=0;for _addgb ,_gcdc :=range _ddg ._agab .Images {if _gcdc ==img {_dcag =_addgb +1;break ;};};var _afgg string ;for _cfge ,_def :=range _ddg ._agab .Slides (){if _def ._fea ==_ddg ._fea {_dfee :=_dc .Sprintf ("\u002e\u002e\u002f\u006ded\u0069\u0061\u002f\u0069\u006d\u0061\u0067\u0065\u0025\u0064\u002e\u0025\u0073",_dcag ,img .Format ());
_eeeb :=_ddg ._agab ._bcd [_cfge ].AddRelationship (_dfee ,_ge .ImageType );_afgg =_eeeb .ID ();};};return _afgg ;};

// PresentationText is an array of extracted text items which has some methods for representing extracted text.
type PresentationText struct{Slides []*SlideText ;};

// GetLayoutImageByRelID returns an ImageRef with the associated relation ID in the
// slide layout.
func (_fec *Slide )GetLayoutImageByRelID (relID string )(_adc .ImageRef ,bool ){_aedb :=_fec .getSlideLayoutRels ();if (_aedb ==_adc .Relationships {}){return _adc .ImageRef {},false ;};_bdcf :=_aedb .GetTargetByRelId (relID );for _ ,_eccb :=range _fec ._agab .Images {if _eccb .Target ()==_bdcf {return _eccb ,true ;
};};return _adc .ImageRef {},false ;};

// GetImageByRelID returns an ImageRef with the associated relation ID in the
// document.
func (_cdca *Presentation )GetImageByRelID (relID string )(_adc .ImageRef ,bool ){for _ ,_dccf :=range _cdca .Images {if _dccf .RelID ()==relID {return _dccf ,true ;};};return _adc .ImageRef {},false ;};func (_ffed *Presentation )saveToFile (_ecg string ,_efbfb bool )error {_cab ,_cgee :=_eg .Create (_ecg );
if _cgee !=nil {return _cgee ;};defer func (){_eaa :=_cab .Close ();if _eaa !=nil {_dd .Log .Error ("\u0045R\u0052\u004f\u0052\u003a\u0020\u0025v",_eaa );};}();return _ffed .save (_cab ,_efbfb );};

// Charts return the array of presentation charts.
func (_eggf *Presentation )Charts ()[]_g .ChartSpace {_bagc :=make ([]_g .ChartSpace ,0);for _ ,_dcccc :=range _eggf ._efa {_bagc =append (_bagc ,*_dcccc .X ());};return _bagc ;};